# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

from CommentView import Ui_Dialog as comment_window 
from AnalysisResultView import Ui_Dialog as analysis_window
from OutputFieldView import Ui_Dialog as output_Field_Window
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def openWindow12(self):
        self.window = QtWidgets.QDialog()
        self.ui = comment_window()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindow11(self):
        self.window = QtWidgets.QDialog()
        self.ui = analysis_window()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindow13(self):
        self.window = QtWidgets.QDialog()
        self.ui = output_Field_Window()
        self.ui.setupUi(self.window)
        self.window.show()
    
        
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1271, 774)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("BEAT-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.projectTab = QtWidgets.QWidget()
        self.projectTab.setAutoFillBackground(True)
        self.projectTab.setStyleSheet("")
        self.projectTab.setObjectName("projectTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.projectTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mainGrid = QtWidgets.QGridLayout()
        self.mainGrid.setObjectName("mainGrid")
        self.titleGrid = QtWidgets.QGridLayout()
        self.titleGrid.setObjectName("titleGrid")
        self.boxGrid = QtWidgets.QGridLayout()
        self.boxGrid.setObjectName("boxGrid")
        self.projectViewGrid = QtWidgets.QGridLayout()
        self.projectViewGrid.setObjectName("projectViewGrid")
        self.project_view = QtWidgets.QLabel(self.projectTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.project_view.setFont(font)
        self.project_view.setAutoFillBackground(False)
        self.project_view.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.project_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.project_view.setAlignment(QtCore.Qt.AlignCenter)
        self.project_view.setObjectName("project_view")
        self.projectViewGrid.addWidget(self.project_view, 0, 0, 1, 1)
        self.projViewBox = QtWidgets.QFrame(self.projectTab)
        self.projViewBox.setFrameShape(QtWidgets.QFrame.Panel)
        self.projViewBox.setObjectName("projViewBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.projViewBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_box = QtWidgets.QLineEdit(self.projViewBox)
        self.search_box.setText("")
        self.search_box.setClearButtonEnabled(True)
        self.search_box.setObjectName("search_box")
        self.verticalLayout.addWidget(self.search_box)
        self.existing_projects = QtWidgets.QListWidget(self.projViewBox)
        self.existing_projects.setAutoFillBackground(True)
        self.existing_projects.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.existing_projects.setObjectName("existing_projects")
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        self.verticalLayout.addWidget(self.existing_projects)
        self.new_project = QtWidgets.QPushButton(self.projViewBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_project.sizePolicy().hasHeightForWidth())
        self.new_project.setSizePolicy(sizePolicy)
        self.new_project.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.new_project.setAutoFillBackground(False)
        self.new_project.setObjectName("new_project")
        self.verticalLayout.addWidget(self.new_project)
        self.gridLayout_10.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.projectViewGrid.addWidget(self.projViewBox, 1, 0, 1, 1)
        self.boxGrid.addLayout(self.projectViewGrid, 0, 0, 1, 1)
        self.detailedProViewGrid = QtWidgets.QGridLayout()
        self.detailedProViewGrid.setObjectName("detailedProViewGrid")
        self.DetailedProjectView = QtWidgets.QLabel(self.projectTab)
        self.DetailedProjectView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetailedProjectView.sizePolicy().hasHeightForWidth())
        self.DetailedProjectView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DetailedProjectView.setFont(font)
        self.DetailedProjectView.setAutoFillBackground(False)
        self.DetailedProjectView.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.DetailedProjectView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DetailedProjectView.setTextFormat(QtCore.Qt.RichText)
        self.DetailedProjectView.setAlignment(QtCore.Qt.AlignCenter)
        self.DetailedProjectView.setObjectName("DetailedProjectView")
        self.detailedProViewGrid.addWidget(self.DetailedProjectView, 0, 0, 1, 1)
        self.dpv_description = QtWidgets.QFrame(self.projectTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpv_description.sizePolicy().hasHeightForWidth())
        self.dpv_description.setSizePolicy(sizePolicy)
        self.dpv_description.setFrameShape(QtWidgets.QFrame.Box)
        self.dpv_description.setObjectName("dpv_description")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.dpv_description)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.binary_properties = QtWidgets.QLabel(self.dpv_description)
        self.binary_properties.setObjectName("binary_properties")
        self.gridLayout_15.addWidget(self.binary_properties, 3, 0, 1, 1)
        self.project_nameBox = QtWidgets.QLineEdit(self.dpv_description)
        self.project_nameBox.setObjectName("project_nameBox")
        self.gridLayout_15.addWidget(self.project_nameBox, 0, 1, 1, 1)
        self.project_name = QtWidgets.QLabel(self.dpv_description)
        self.project_name.setObjectName("project_name")
        self.gridLayout_15.addWidget(self.project_name, 0, 0, 1, 1)
        self.project_description = QtWidgets.QLabel(self.dpv_description)
        self.project_description.setObjectName("project_description")
        self.gridLayout_15.addWidget(self.project_description, 1, 0, 1, 1)
        self.filePathBox = QtWidgets.QLineEdit(self.dpv_description)
        self.filePathBox.setObjectName("filePathBox")
        self.gridLayout_15.addWidget(self.filePathBox, 2, 1, 1, 1)
        self.description_box = QtWidgets.QTextEdit(self.dpv_description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_box.sizePolicy().hasHeightForWidth())
        self.description_box.setSizePolicy(sizePolicy)
        self.description_box.setObjectName("description_box")
        self.gridLayout_15.addWidget(self.description_box, 1, 1, 1, 1)
        self.browse = QtWidgets.QPushButton(self.dpv_description)
        self.browse.setObjectName("browse")
        self.gridLayout_15.addWidget(self.browse, 2, 2, 1, 1)
        self.save = QtWidgets.QPushButton(self.dpv_description)
        self.save.setAutoDefault(False)
        self.save.setDefault(True)
        self.save.setFlat(False)
        self.save.setObjectName("save")
        self.gridLayout_15.addWidget(self.save, 4, 2, 1, 1)
        self.delete_2 = QtWidgets.QPushButton(self.dpv_description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_2.sizePolicy().hasHeightForWidth())
        self.delete_2.setSizePolicy(sizePolicy)
        self.delete_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.delete_2.setObjectName("delete_2")
        self.gridLayout_15.addWidget(self.delete_2, 4, 1, 1, 1)
        self.file_path = QtWidgets.QLabel(self.dpv_description)
        self.file_path.setObjectName("file_path")
        self.gridLayout_15.addWidget(self.file_path, 2, 0, 1, 1)
        self.binaryPropTable = QtWidgets.QTableWidget(self.dpv_description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.binaryPropTable.sizePolicy().hasHeightForWidth())
        self.binaryPropTable.setSizePolicy(sizePolicy)
        self.binaryPropTable.setMaximumSize(QtCore.QSize(346, 16777215))
        self.binaryPropTable.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.binaryPropTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.binaryPropTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.binaryPropTable.setAlternatingRowColors(True)
        self.binaryPropTable.setShowGrid(True)
        self.binaryPropTable.setWordWrap(False)
        self.binaryPropTable.setObjectName("binaryPropTable")
        self.binaryPropTable.setColumnCount(2)
        self.binaryPropTable.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(12, 0, item)
        self.binaryPropTable.horizontalHeader().setVisible(False)
        self.binaryPropTable.horizontalHeader().setCascadingSectionResizes(True)
        self.binaryPropTable.horizontalHeader().setMinimumSectionSize(100)
        self.binaryPropTable.horizontalHeader().setStretchLastSection(True)
        self.binaryPropTable.verticalHeader().setVisible(False)
        self.binaryPropTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_15.addWidget(self.binaryPropTable, 3, 1, 1, 1)
        self.detailedProViewGrid.addWidget(self.dpv_description, 1, 0, 1, 1)
        self.boxGrid.addLayout(self.detailedProViewGrid, 0, 1, 1, 1)
        self.boxGrid.setColumnStretch(0, 2)
        self.boxGrid.setColumnStretch(1, 8)
        self.titleGrid.addLayout(self.boxGrid, 0, 0, 1, 1)
        self.mainGrid.addLayout(self.titleGrid, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.mainGrid, 0, 0, 1, 1)
        self.tabWidget.addTab(self.projectTab, "")
        self.analysisTab = QtWidgets.QWidget()
        self.analysisTab.setObjectName("analysisTab")
        self.label_16 = QtWidgets.QLabel(self.analysisTab)
        self.label_16.setGeometry(QtCore.QRect(80, 20, 47, 13))
        self.label_16.setObjectName("label_16")
        self.pushButton_11 = QtWidgets.QPushButton(self.analysisTab)
        self.pushButton_11.setGeometry(QtCore.QRect(870, 120, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        ############ Button A from Analysis Window
        self.pushButton_11.clicked.connect(self.openWindow11)
        

        self.checkBox_16 = QtWidgets.QCheckBox(self.analysisTab)
        self.checkBox_16.setGeometry(QtCore.QRect(51, 287, 110, 17))
        self.checkBox_16.setObjectName("checkBox_16")
        self.pushButton_12 = QtWidgets.QPushButton(self.analysisTab)
        self.pushButton_12.setGeometry(QtCore.QRect(870, 180, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        ############ Button O from Analysis Window
        self.pushButton_12.clicked.connect(self.openWindow12)
        
        
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.analysisTab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(330, 150, 491, 321))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.DynamicAnalysisRunButton_3 = QtWidgets.QPushButton(self.analysisTab)
        self.DynamicAnalysisRunButton_3.setGeometry(QtCore.QRect(370, 50, 75, 23))
        self.DynamicAnalysisRunButton_3.setObjectName("DynamicAnalysisRunButton_3")
        self.label_15 = QtWidgets.QLabel(self.analysisTab)
        self.label_15.setGeometry(QtCore.QRect(270, 50, 81, 20))
        self.label_15.setObjectName("label_15")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.analysisTab)
        self.textBrowser_7.setGeometry(QtCore.QRect(331, 151, 489, 156))
        self.textBrowser_7.setStyleSheet("color: #616161;\n"
"background-color: rgb(235, 229, 233);\n"
"text-shadow: #e0e0e0 1px 1px 0;\n"
"")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.label_14 = QtWidgets.QLabel(self.analysisTab)
        self.label_14.setGeometry(QtCore.QRect(46, 50, 81, 20))
        self.label_14.setObjectName("label_14")
        self.StaticAnalysisRunButton_3 = QtWidgets.QPushButton(self.analysisTab)
        self.StaticAnalysisRunButton_3.setGeometry(QtCore.QRect(130, 50, 75, 23))
        self.StaticAnalysisRunButton_3.setObjectName("StaticAnalysisRunButton_3")
        self.checkBox_15 = QtWidgets.QCheckBox(self.analysisTab)
        self.checkBox_15.setGeometry(QtCore.QRect(51, 340, 110, 17))
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.analysisTab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 150, 251, 321))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_46.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.checkBox_13 = QtWidgets.QCheckBox(self.analysisTab)
        self.checkBox_13.setGeometry(QtCore.QRect(51, 234, 111, 17))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.analysisTab)
        self.checkBox_14.setGeometry(QtCore.QRect(51, 181, 112, 17))
        self.checkBox_14.setObjectName("checkBox_14")
        self.pushButton_13 = QtWidgets.QPushButton(self.analysisTab)
        self.pushButton_13.setGeometry(QtCore.QRect(870, 150, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.comboBox_6 = QtWidgets.QComboBox(self.analysisTab)
        ############ Button A from Analysis Window
        self.pushButton_13.clicked.connect(self.openWindow13)
        
        self.comboBox_6.setGeometry(QtCore.QRect(130, 90, 69, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.analysisTab)
        self.comboBox_5.setGeometry(QtCore.QRect(130, 20, 69, 22))
        self.comboBox_5.setStyleSheet("opacity:0.5")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.label_13 = QtWidgets.QLabel(self.analysisTab)
        self.label_13.setGeometry(QtCore.QRect(16, 90, 111, 20))
        self.label_13.setObjectName("label_13")
        self.project_view_15 = QtWidgets.QLabel(self.analysisTab)
        self.project_view_15.setGeometry(QtCore.QRect(50, 130, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.project_view_15.setFont(font)
        self.project_view_15.setAutoFillBackground(False)
        self.project_view_15.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.project_view_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.project_view_15.setAlignment(QtCore.Qt.AlignCenter)
        self.project_view_15.setObjectName("project_view_15")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.analysisTab)
        self.textBrowser_8.setGeometry(QtCore.QRect(331, 313, 489, 157))
        self.textBrowser_8.setStyleSheet("color: #616161;\n"
" background-color: rgb(235, 229, 233);\n"
"text-shadow: #e0e0e0 1px 1px 0;")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.DetailedProjectView_15 = QtWidgets.QLabel(self.analysisTab)
        self.DetailedProjectView_15.setEnabled(True)
        self.DetailedProjectView_15.setGeometry(QtCore.QRect(330, 130, 491, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetailedProjectView_15.sizePolicy().hasHeightForWidth())
        self.DetailedProjectView_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DetailedProjectView_15.setFont(font)
        self.DetailedProjectView_15.setAutoFillBackground(False)
        self.DetailedProjectView_15.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.DetailedProjectView_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DetailedProjectView_15.setTextFormat(QtCore.Qt.RichText)
        self.DetailedProjectView_15.setAlignment(QtCore.Qt.AlignCenter)
        self.DetailedProjectView_15.setObjectName("DetailedProjectView_15")
        self.StopButtton_3 = QtWidgets.QPushButton(self.analysisTab)
        self.StopButtton_3.setGeometry(QtCore.QRect(450, 50, 75, 23))
        self.StopButtton_3.setObjectName("StopButtton_3")
        self.tabWidget.addTab(self.analysisTab, "")
        self.pluginTab = QtWidgets.QWidget()
        self.pluginTab.setObjectName("pluginTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pluginTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mainGrid_2 = QtWidgets.QGridLayout()
        self.mainGrid_2.setObjectName("mainGrid_2")
        self.titleGrid_2 = QtWidgets.QGridLayout()
        self.titleGrid_2.setObjectName("titleGrid_2")
        self.boxGrid_2 = QtWidgets.QGridLayout()
        self.boxGrid_2.setObjectName("boxGrid_2")
        self.projectViewGrid_2 = QtWidgets.QGridLayout()
        self.projectViewGrid_2.setObjectName("projectViewGrid_2")
        self.project_view_2 = QtWidgets.QLabel(self.pluginTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.project_view_2.setFont(font)
        self.project_view_2.setAutoFillBackground(False)
        self.project_view_2.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.project_view_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.project_view_2.setAlignment(QtCore.Qt.AlignCenter)
        self.project_view_2.setObjectName("project_view_2")
        self.projectViewGrid_2.addWidget(self.project_view_2, 0, 0, 1, 1)
        self.projViewBox_2 = QtWidgets.QFrame(self.pluginTab)
        self.projViewBox_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.projViewBox_2.setObjectName("projViewBox_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.projViewBox_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_box_2 = QtWidgets.QLineEdit(self.projViewBox_2)
        self.search_box_2.setText("")
        self.search_box_2.setClearButtonEnabled(True)
        self.search_box_2.setObjectName("search_box_2")
        self.verticalLayout_2.addWidget(self.search_box_2)
        self.existing_projects_2 = QtWidgets.QListWidget(self.projViewBox_2)
        self.existing_projects_2.setAutoFillBackground(True)
        self.existing_projects_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.existing_projects_2.setObjectName("existing_projects_2")
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        self.verticalLayout_2.addWidget(self.existing_projects_2)
        self.new_project_2 = QtWidgets.QPushButton(self.projViewBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_project_2.sizePolicy().hasHeightForWidth())
        self.new_project_2.setSizePolicy(sizePolicy)
        self.new_project_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.new_project_2.setAutoFillBackground(False)
        self.new_project_2.setObjectName("new_project_2")
        self.verticalLayout_2.addWidget(self.new_project_2)
        self.gridLayout_11.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.projectViewGrid_2.addWidget(self.projViewBox_2, 1, 0, 1, 1)
        self.boxGrid_2.addLayout(self.projectViewGrid_2, 0, 0, 1, 1)
        self.detailedProViewGrid_2 = QtWidgets.QGridLayout()
        self.detailedProViewGrid_2.setObjectName("detailedProViewGrid_2")
        self.DetailedProjectView_2 = QtWidgets.QLabel(self.pluginTab)
        self.DetailedProjectView_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetailedProjectView_2.sizePolicy().hasHeightForWidth())
        self.DetailedProjectView_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DetailedProjectView_2.setFont(font)
        self.DetailedProjectView_2.setAutoFillBackground(False)
        self.DetailedProjectView_2.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.DetailedProjectView_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DetailedProjectView_2.setTextFormat(QtCore.Qt.RichText)
        self.DetailedProjectView_2.setAlignment(QtCore.Qt.AlignCenter)
        self.DetailedProjectView_2.setObjectName("DetailedProjectView_2")
        self.detailedProViewGrid_2.addWidget(self.DetailedProjectView_2, 0, 0, 1, 1)
        self.dpv_description_2 = QtWidgets.QFrame(self.pluginTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpv_description_2.sizePolicy().hasHeightForWidth())
        self.dpv_description_2.setSizePolicy(sizePolicy)
        self.dpv_description_2.setFrameShape(QtWidgets.QFrame.Box)
        self.dpv_description_2.setObjectName("dpv_description_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.dpv_description_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_3 = QtWidgets.QLabel(self.dpv_description_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_16.addWidget(self.label_3, 5, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.dpv_description_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_16.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.file_path_2 = QtWidgets.QLabel(self.dpv_description_2)
        self.file_path_2.setObjectName("file_path_2")
        self.gridLayout_16.addWidget(self.file_path_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.dpv_description_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_16.addWidget(self.label_4, 3, 0, 1, 1)
        self.project_nameBox_2 = QtWidgets.QLineEdit(self.dpv_description_2)
        self.project_nameBox_2.setObjectName("project_nameBox_2")
        self.gridLayout_16.addWidget(self.project_nameBox_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem, 7, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem1, 9, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.dpv_description_2)
        self.label.setObjectName("label")
        self.gridLayout_16.addWidget(self.label, 1, 0, 1, 1)
        self.project_name_2 = QtWidgets.QLabel(self.dpv_description_2)
        self.project_name_2.setObjectName("project_name_2")
        self.gridLayout_16.addWidget(self.project_name_2, 0, 0, 1, 1)
        self.filePathBox_2 = QtWidgets.QLineEdit(self.dpv_description_2)
        self.filePathBox_2.setObjectName("filePathBox_2")
        self.gridLayout_16.addWidget(self.filePathBox_2, 2, 1, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.dpv_description_2)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_16.addWidget(self.textEdit_2, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem2, 8, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.dpv_description_2)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_16.addWidget(self.comboBox, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.dpv_description_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_16.addWidget(self.pushButton, 1, 2, 1, 1)
        self.save_2 = QtWidgets.QPushButton(self.dpv_description_2)
        self.save_2.setAutoDefault(False)
        self.save_2.setDefault(True)
        self.save_2.setFlat(False)
        self.save_2.setObjectName("save_2")
        self.gridLayout_16.addWidget(self.save_2, 10, 2, 1, 1)
        self.delete_3 = QtWidgets.QPushButton(self.dpv_description_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_3.sizePolicy().hasHeightForWidth())
        self.delete_3.setSizePolicy(sizePolicy)
        self.delete_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.delete_3.setObjectName("delete_3")
        self.gridLayout_16.addWidget(self.delete_3, 10, 0, 1, 1)
        self.browse_2 = QtWidgets.QPushButton(self.dpv_description_2)
        self.browse_2.setObjectName("browse_2")
        self.gridLayout_16.addWidget(self.browse_2, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dpv_description_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_16.addWidget(self.label_2, 4, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.dpv_description_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_16.addWidget(self.textEdit, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem3, 6, 1, 1, 1)
        self.detailedProViewGrid_2.addWidget(self.dpv_description_2, 1, 0, 1, 1)
        self.boxGrid_2.addLayout(self.detailedProViewGrid_2, 0, 1, 1, 1)
        self.boxGrid_2.setColumnStretch(0, 2)
        self.boxGrid_2.setColumnStretch(1, 8)
        self.titleGrid_2.addLayout(self.boxGrid_2, 0, 0, 1, 1)
        self.mainGrid_2.addLayout(self.titleGrid_2, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.mainGrid_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pluginTab, "")
        self.PoiTab = QtWidgets.QWidget()
        self.PoiTab.setObjectName("PoiTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.PoiTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.titleGrid_6 = QtWidgets.QGridLayout()
        self.titleGrid_6.setObjectName("titleGrid_6")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gridFrame_6 = QtWidgets.QFrame(self.PoiTab)
        self.gridFrame_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.gridFrame_6.setObjectName("gridFrame_6")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.gridFrame_6)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.POI_NewButton = QtWidgets.QPushButton(self.gridFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.POI_NewButton.sizePolicy().hasHeightForWidth())
        self.POI_NewButton.setSizePolicy(sizePolicy)
        self.POI_NewButton.setAutoFillBackground(False)
        self.POI_NewButton.setObjectName("POI_NewButton")
        self.gridLayout_29.addWidget(self.POI_NewButton, 2, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.POI_List = QtWidgets.QListWidget(self.gridFrame_6)
        self.POI_List.setObjectName("POI_List")
        item = QtWidgets.QListWidgetItem()
        self.POI_List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.POI_List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.POI_List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.POI_List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.POI_List.addItem(item)
        self.verticalLayout_8.addWidget(self.POI_List)
        self.gridLayout_29.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        self.POI_LineEdit = QtWidgets.QLineEdit(self.gridFrame_6)
        self.POI_LineEdit.setObjectName("POI_LineEdit")
        self.gridLayout_29.addWidget(self.POI_LineEdit, 0, 1, 1, 1)
        self.gridLayout_28.addWidget(self.gridFrame_6, 1, 0, 1, 1)
        self.POI_LabelView = QtWidgets.QLabel(self.PoiTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.POI_LabelView.setFont(font)
        self.POI_LabelView.setAutoFillBackground(False)
        self.POI_LabelView.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.POI_LabelView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.POI_LabelView.setAlignment(QtCore.Qt.AlignCenter)
        self.POI_LabelView.setObjectName("POI_LabelView")
        self.gridLayout_28.addWidget(self.POI_LabelView, 0, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_28, 0, 0, 1, 1)
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.POI_DetailLabel_2 = QtWidgets.QLabel(self.PoiTab)
        self.POI_DetailLabel_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.POI_DetailLabel_2.sizePolicy().hasHeightForWidth())
        self.POI_DetailLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.POI_DetailLabel_2.setFont(font)
        self.POI_DetailLabel_2.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.POI_DetailLabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.POI_DetailLabel_2.setTextFormat(QtCore.Qt.RichText)
        self.POI_DetailLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.POI_DetailLabel_2.setObjectName("POI_DetailLabel_2")
        self.gridLayout_32.addWidget(self.POI_DetailLabel_2, 0, 0, 1, 1)
        self.gridFrame_12 = QtWidgets.QFrame(self.PoiTab)
        self.gridFrame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame_12.setObjectName("gridFrame_12")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.gridFrame_12)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.POI_Label2_2 = QtWidgets.QLabel(self.gridFrame_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.POI_Label2_2.setFont(font)
        self.POI_Label2_2.setObjectName("POI_Label2_2")
        self.gridLayout_33.addWidget(self.POI_Label2_2, 2, 0, 1, 1)
        self.POI_Del_2 = QtWidgets.QPushButton(self.gridFrame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.POI_Del_2.sizePolicy().hasHeightForWidth())
        self.POI_Del_2.setSizePolicy(sizePolicy)
        self.POI_Del_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.POI_Del_2.setObjectName("POI_Del_2")
        self.gridLayout_33.addWidget(self.POI_Del_2, 4, 0, 1, 1)
        self.POI_Combo2_2 = QtWidgets.QComboBox(self.gridFrame_12)
        self.POI_Combo2_2.setObjectName("POI_Combo2_2")
        self.POI_Combo2_2.addItem("")
        self.gridLayout_33.addWidget(self.POI_Combo2_2, 2, 1, 1, 1)
        self.POI_Combo1_3 = QtWidgets.QComboBox(self.gridFrame_12)
        self.POI_Combo1_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.POI_Combo1_3.setObjectName("POI_Combo1_3")
        self.POI_Combo1_3.addItem("")
        self.gridLayout_33.addWidget(self.POI_Combo1_3, 0, 1, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.POI_Label1_2 = QtWidgets.QLabel(self.gridFrame_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.POI_Label1_2.setFont(font)
        self.POI_Label1_2.setObjectName("POI_Label1_2")
        self.verticalLayout_10.addWidget(self.POI_Label1_2)
        self.gridLayout_33.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.POI_Panel_2 = QtWidgets.QTableView(self.gridFrame_12)
        self.POI_Panel_2.setObjectName("POI_Panel_2")
        self.gridLayout_33.addWidget(self.POI_Panel_2, 3, 0, 1, 3)
        self.POI_Save_2 = QtWidgets.QPushButton(self.gridFrame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.POI_Save_2.sizePolicy().hasHeightForWidth())
        self.POI_Save_2.setSizePolicy(sizePolicy)
        self.POI_Save_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.POI_Save_2.setAutoDefault(False)
        self.POI_Save_2.setDefault(True)
        self.POI_Save_2.setFlat(False)
        self.POI_Save_2.setObjectName("POI_Save_2")
        self.gridLayout_33.addWidget(self.POI_Save_2, 4, 2, 1, 1)
        self.gridLayout_32.addWidget(self.gridFrame_12, 2, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_32, 0, 1, 1, 1)
        self.gridLayout_27.setColumnStretch(0, 2)
        self.gridLayout_27.setColumnStretch(1, 8)
        self.titleGrid_6.addLayout(self.gridLayout_27, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.titleGrid_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.PoiTab, "")
        self.documentationTab = QtWidgets.QWidget()
        self.documentationTab.setObjectName("documentationTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.documentationTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainGrid_5 = QtWidgets.QGridLayout()
        self.mainGrid_5.setObjectName("mainGrid_5")
        self.titleGrid_5 = QtWidgets.QGridLayout()
        self.titleGrid_5.setObjectName("titleGrid_5")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.documentation_view = QtWidgets.QLabel(self.documentationTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.documentation_view.setFont(font)
        self.documentation_view.setAutoFillBackground(False)
        self.documentation_view.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.documentation_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.documentation_view.setAlignment(QtCore.Qt.AlignCenter)
        self.documentation_view.setObjectName("documentation_view")
        self.gridLayout_14.addWidget(self.documentation_view, 0, 0, 1, 1)
        self.gridFrame_3 = QtWidgets.QFrame(self.documentationTab)
        self.gridFrame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.documentation_lineEdit = QtWidgets.QLineEdit(self.gridFrame_3)
        self.documentation_lineEdit.setObjectName("documentation_lineEdit")
        self.verticalLayout_5.addWidget(self.documentation_lineEdit)
        self.documentation_list = QtWidgets.QListWidget(self.gridFrame_3)
        self.documentation_list.setObjectName("documentation_list")
        item = QtWidgets.QListWidgetItem()
        self.documentation_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.documentation_list.addItem(item)
        self.verticalLayout_5.addWidget(self.documentation_list)
        self.gridLayout_19.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.gridFrame_3, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.documentation_detail = QtWidgets.QLabel(self.documentationTab)
        self.documentation_detail.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.documentation_detail.sizePolicy().hasHeightForWidth())
        self.documentation_detail.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.documentation_detail.setFont(font)
        self.documentation_detail.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.documentation_detail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.documentation_detail.setTextFormat(QtCore.Qt.RichText)
        self.documentation_detail.setAlignment(QtCore.Qt.AlignCenter)
        self.documentation_detail.setObjectName("documentation_detail")
        self.gridLayout_20.addWidget(self.documentation_detail, 0, 0, 1, 1)
        self.gridFrame_8 = QtWidgets.QFrame(self.documentationTab)
        self.gridFrame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame_8.setObjectName("gridFrame_8")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.gridFrame_8)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.documentation_panel = QtWidgets.QTableView(self.gridFrame_8)
        self.documentation_panel.setObjectName("documentation_panel")
        self.gridLayout_21.addWidget(self.documentation_panel, 1, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_21.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.gridFrame_8, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_20, 0, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 2)
        self.gridLayout_7.setColumnStretch(1, 8)
        self.titleGrid_5.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.mainGrid_5.addLayout(self.titleGrid_5, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.mainGrid_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.documentationTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1271, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.existing_projects.setCurrentRow(-1)
        self.existing_projects_2.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BEAT: Behavior Extraction and Analysis Tool"))
        self.project_view.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Project View</span></p></body></html>"))
        self.search_box.setPlaceholderText(_translate("MainWindow", "Search Project"))
        self.existing_projects.setSortingEnabled(False)
        __sortingEnabled = self.existing_projects.isSortingEnabled()
        self.existing_projects.setSortingEnabled(False)
        item = self.existing_projects.item(0)
        item.setText(_translate("MainWindow", "Project A"))
        item = self.existing_projects.item(1)
        item.setText(_translate("MainWindow", "Project B"))
        item = self.existing_projects.item(2)
        item.setText(_translate("MainWindow", "Project C"))
        item = self.existing_projects.item(3)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects.item(4)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects.item(5)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects.item(6)
        item.setText(_translate("MainWindow", "Project X"))
        self.existing_projects.setSortingEnabled(__sortingEnabled)
        self.new_project.setText(_translate("MainWindow", "New"))
        self.DetailedProjectView.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Project View</span></p></body></html>"))
        self.binary_properties.setText(_translate("MainWindow", "Binary File \n"
"Properties"))
        self.project_name.setText(_translate("MainWindow", "Project Name"))
        self.project_description.setText(_translate("MainWindow", "Project \n"
"Description"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.delete_2.setText(_translate("MainWindow", "Delete"))
        self.file_path.setText(_translate("MainWindow", "Binary File Path"))
        item = self.binaryPropTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.binaryPropTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.binaryPropTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.binaryPropTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.binaryPropTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.binaryPropTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.binaryPropTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.binaryPropTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.binaryPropTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.binaryPropTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.binaryPropTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.binaryPropTable.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.binaryPropTable.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.binaryPropTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.binaryPropTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.binaryPropTable.isSortingEnabled()
        self.binaryPropTable.setSortingEnabled(False)
        item = self.binaryPropTable.item(0, 0)
        item.setText(_translate("MainWindow", "OS"))
        item = self.binaryPropTable.item(1, 0)
        item.setText(_translate("MainWindow", "Binary Type"))
        item = self.binaryPropTable.item(2, 0)
        item.setText(_translate("MainWindow", "Machine"))
        item = self.binaryPropTable.item(3, 0)
        item.setText(_translate("MainWindow", "Class"))
        item = self.binaryPropTable.item(4, 0)
        item.setText(_translate("MainWindow", "Bits"))
        item = self.binaryPropTable.item(5, 0)
        item.setText(_translate("MainWindow", "Language"))
        item = self.binaryPropTable.item(6, 0)
        item.setText(_translate("MainWindow", "Canary"))
        item = self.binaryPropTable.item(7, 0)
        item.setText(_translate("MainWindow", "Crypto"))
        item = self.binaryPropTable.item(8, 0)
        item.setText(_translate("MainWindow", "Nx"))
        item = self.binaryPropTable.item(9, 0)
        item.setText(_translate("MainWindow", "Pic"))
        item = self.binaryPropTable.item(10, 0)
        item.setText(_translate("MainWindow", "Relocs"))
        item = self.binaryPropTable.item(11, 0)
        item.setText(_translate("MainWindow", "Relro"))
        item = self.binaryPropTable.item(12, 0)
        item.setText(_translate("MainWindow", "Stripped"))
        self.binaryPropTable.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("MainWindow", "Project"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>Plug in</p></body></html>"))
        self.pushButton_11.setText(_translate("MainWindow", "A"))
        self.checkBox_16.setText(_translate("MainWindow", "Point of interest C"))
        self.pushButton_12.setText(_translate("MainWindow", "C"))
        self.DynamicAnalysisRunButton_3.setText(_translate("MainWindow", "Run"))
        self.label_15.setText(_translate("MainWindow", "Dynamic Analysis"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Point of Interest Content Area</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "Static Analysis"))
        self.StaticAnalysisRunButton_3.setText(_translate("MainWindow", "Run"))
        self.checkBox_15.setText(_translate("MainWindow", "Point of interest D"))
        self.checkBox_13.setText(_translate("MainWindow", "Point of Interest B"))
        self.checkBox_14.setText(_translate("MainWindow", "Point of Interest A"))
        self.pushButton_13.setText(_translate("MainWindow", "O"))
        self.comboBox_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Type</p></body></html>"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Type"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Existing Plugin"))
        self.label_13.setText(_translate("MainWindow", "Point of Interest Type"))
        self.project_view_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Project View</span></p></body></html>"))
        self.textBrowser_8.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Point of Interest Content Area</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Terminal Window Content Area</p></body></html>"))
        self.DetailedProjectView_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Project View</span></p></body></html>"))
        self.StopButtton_3.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysisTab), _translate("MainWindow", "Analysis "))
        self.project_view_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Plugin View</span></p></body></html>"))
        self.search_box_2.setPlaceholderText(_translate("MainWindow", "Search Project"))
        self.existing_projects_2.setSortingEnabled(False)
        __sortingEnabled = self.existing_projects_2.isSortingEnabled()
        self.existing_projects_2.setSortingEnabled(False)
        item = self.existing_projects_2.item(0)
        item.setText(_translate("MainWindow", "Plugin A"))
        item = self.existing_projects_2.item(1)
        item.setText(_translate("MainWindow", "Plugin B"))
        item = self.existing_projects_2.item(2)
        item.setText(_translate("MainWindow", "Plugin C"))
        item = self.existing_projects_2.item(3)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_2.item(4)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_2.item(5)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_2.item(6)
        item.setText(_translate("MainWindow", "Plugin X"))
        self.existing_projects_2.setSortingEnabled(__sortingEnabled)
        self.new_project_2.setText(_translate("MainWindow", "New"))
        self.DetailedProjectView_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Plugin View</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Points of Interest"))
        self.file_path_2.setText(_translate("MainWindow", "Plugin Name"))
        self.label_4.setText(_translate("MainWindow", "Plugin Description"))
        self.label.setText(_translate("MainWindow", "Plugin Predefined Data Set"))
        self.project_name_2.setText(_translate("MainWindow", "Plugin Structure"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.save_2.setText(_translate("MainWindow", "Save"))
        self.delete_3.setText(_translate("MainWindow", "Delete"))
        self.browse_2.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Default Output Field"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pluginTab), _translate("MainWindow", "Plugin Management"))
        self.POI_NewButton.setText(_translate("MainWindow", "New"))
        __sortingEnabled = self.POI_List.isSortingEnabled()
        self.POI_List.setSortingEnabled(False)
        item = self.POI_List.item(0)
        item.setText(_translate("MainWindow", "Point of interest A"))
        item = self.POI_List.item(1)
        item.setText(_translate("MainWindow", "Point of interest B"))
        item = self.POI_List.item(2)
        item.setText(_translate("MainWindow", "Point of interest C"))
        item = self.POI_List.item(3)
        item.setText(_translate("MainWindow", "             ... "))
        item = self.POI_List.item(4)
        item.setText(_translate("MainWindow", "Point of interest X"))
        self.POI_List.setSortingEnabled(__sortingEnabled)
        self.POI_LineEdit.setText(_translate("MainWindow", "Points of Interest"))
        self.POI_LabelView.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Point of Interest View</span></p></body></html>"))
        self.POI_DetailLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Point of Interest View</span></p></body></html>"))
        self.POI_Label2_2.setText(_translate("MainWindow", "Point of Interest Type"))
        self.POI_Del_2.setText(_translate("MainWindow", "Delete"))
        self.POI_Combo2_2.setItemText(0, _translate("MainWindow", "Type"))
        self.POI_Combo1_3.setItemText(0, _translate("MainWindow", "Existing Plugin"))
        self.POI_Label1_2.setText(_translate("MainWindow", "Plugin"))
        self.POI_Save_2.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PoiTab), _translate("MainWindow", "Points of Interest"))
        self.documentation_view.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Document View</span></p></body></html>"))
        self.documentation_lineEdit.setText(_translate("MainWindow", "Document"))
        __sortingEnabled = self.documentation_list.isSortingEnabled()
        self.documentation_list.setSortingEnabled(False)
        item = self.documentation_list.item(0)
        item.setText(_translate("MainWindow", "Beat Documentation"))
        item = self.documentation_list.item(1)
        item.setText(_translate("MainWindow", "Plugin Structure"))
        self.documentation_list.setSortingEnabled(__sortingEnabled)
        self.documentation_detail.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Document View</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documentationTab), _translate("MainWindow", "Documentation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
