# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 718)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("BEAT-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.analysisTab = QtWidgets.QWidget()
        self.analysisTab.setObjectName("analysisTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.analysisTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mainGrid_3 = QtWidgets.QGridLayout()
        self.mainGrid_3.setObjectName("mainGrid_3")
        self.titleGrid_3 = QtWidgets.QGridLayout()
        self.titleGrid_3.setObjectName("titleGrid_3")
        self.boxGrid_3 = QtWidgets.QGridLayout()
        self.boxGrid_3.setObjectName("boxGrid_3")
        self.projectViewGrid_3 = QtWidgets.QGridLayout()
        self.projectViewGrid_3.setObjectName("projectViewGrid_3")
        self.project_view_3 = QtWidgets.QLabel(self.analysisTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.project_view_3.setFont(font)
        self.project_view_3.setAutoFillBackground(False)
        self.project_view_3.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.project_view_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.project_view_3.setAlignment(QtCore.Qt.AlignCenter)
        self.project_view_3.setObjectName("project_view_3")
        self.projectViewGrid_3.addWidget(self.project_view_3, 0, 0, 1, 1)
        self.projViewBox_3 = QtWidgets.QFrame(self.analysisTab)
        self.projViewBox_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.projViewBox_3.setObjectName("projViewBox_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.projViewBox_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.search_box_3 = QtWidgets.QLineEdit(self.projViewBox_3)
        self.search_box_3.setText("")
        self.search_box_3.setClearButtonEnabled(True)
        self.search_box_3.setObjectName("search_box_3")
        self.verticalLayout_3.addWidget(self.search_box_3)
        self.existing_projects_3 = QtWidgets.QListWidget(self.projViewBox_3)
        self.existing_projects_3.setAutoFillBackground(True)
        self.existing_projects_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.existing_projects_3.setObjectName("existing_projects_3")
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_3.addItem(item)
        self.verticalLayout_3.addWidget(self.existing_projects_3)
        self.new_project_3 = QtWidgets.QPushButton(self.projViewBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_project_3.sizePolicy().hasHeightForWidth())
        self.new_project_3.setSizePolicy(sizePolicy)
        self.new_project_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.new_project_3.setAutoFillBackground(False)
        self.new_project_3.setObjectName("new_project_3")
        self.verticalLayout_3.addWidget(self.new_project_3)
        self.gridLayout_12.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.projectViewGrid_3.addWidget(self.projViewBox_3, 1, 0, 1, 1)
        self.boxGrid_3.addLayout(self.projectViewGrid_3, 0, 0, 1, 1)
        self.detailedProViewGrid_3 = QtWidgets.QGridLayout()
        self.detailedProViewGrid_3.setObjectName("detailedProViewGrid_3")
        self.DetailedProjectView_3 = QtWidgets.QLabel(self.analysisTab)
        self.DetailedProjectView_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetailedProjectView_3.sizePolicy().hasHeightForWidth())
        self.DetailedProjectView_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DetailedProjectView_3.setFont(font)
        self.DetailedProjectView_3.setAutoFillBackground(False)
        self.DetailedProjectView_3.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.DetailedProjectView_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DetailedProjectView_3.setTextFormat(QtCore.Qt.RichText)
        self.DetailedProjectView_3.setAlignment(QtCore.Qt.AlignCenter)
        self.DetailedProjectView_3.setObjectName("DetailedProjectView_3")
        self.detailedProViewGrid_3.addWidget(self.DetailedProjectView_3, 0, 0, 1, 1)
        self.dpv_description_3 = QtWidgets.QFrame(self.analysisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpv_description_3.sizePolicy().hasHeightForWidth())
        self.dpv_description_3.setSizePolicy(sizePolicy)
        self.dpv_description_3.setFrameShape(QtWidgets.QFrame.Box)
        self.dpv_description_3.setObjectName("dpv_description_3")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.dpv_description_3)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.project_name_3 = QtWidgets.QLabel(self.dpv_description_3)
        self.project_name_3.setObjectName("project_name_3")
        self.gridLayout_17.addWidget(self.project_name_3, 0, 0, 1, 1)
        self.description_box_3 = QtWidgets.QTextEdit(self.dpv_description_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_box_3.sizePolicy().hasHeightForWidth())
        self.description_box_3.setSizePolicy(sizePolicy)
        self.description_box_3.setObjectName("description_box_3")
        self.gridLayout_17.addWidget(self.description_box_3, 1, 1, 1, 1)
        self.file_path_3 = QtWidgets.QLabel(self.dpv_description_3)
        self.file_path_3.setObjectName("file_path_3")
        self.gridLayout_17.addWidget(self.file_path_3, 2, 0, 1, 1)
        self.binary_properties_3 = QtWidgets.QLabel(self.dpv_description_3)
        self.binary_properties_3.setObjectName("binary_properties_3")
        self.gridLayout_17.addWidget(self.binary_properties_3, 3, 0, 1, 1)
        self.project_nameBox_3 = QtWidgets.QLineEdit(self.dpv_description_3)
        self.project_nameBox_3.setObjectName("project_nameBox_3")
        self.gridLayout_17.addWidget(self.project_nameBox_3, 0, 1, 1, 1)
        self.filePathBox_3 = QtWidgets.QLineEdit(self.dpv_description_3)
        self.filePathBox_3.setObjectName("filePathBox_3")
        self.gridLayout_17.addWidget(self.filePathBox_3, 2, 1, 1, 1)
        self.project_description_3 = QtWidgets.QLabel(self.dpv_description_3)
        self.project_description_3.setObjectName("project_description_3")
        self.gridLayout_17.addWidget(self.project_description_3, 1, 0, 1, 1)
        self.binaryPropTable_3 = QtWidgets.QTableWidget(self.dpv_description_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.binaryPropTable_3.sizePolicy().hasHeightForWidth())
        self.binaryPropTable_3.setSizePolicy(sizePolicy)
        self.binaryPropTable_3.setMaximumSize(QtCore.QSize(346, 16777215))
        self.binaryPropTable_3.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.binaryPropTable_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.binaryPropTable_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.binaryPropTable_3.setAlternatingRowColors(True)
        self.binaryPropTable_3.setShowGrid(True)
        self.binaryPropTable_3.setWordWrap(False)
        self.binaryPropTable_3.setObjectName("binaryPropTable_3")
        self.binaryPropTable_3.setColumnCount(2)
        self.binaryPropTable_3.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_3.setItem(12, 0, item)
        self.binaryPropTable_3.horizontalHeader().setVisible(False)
        self.binaryPropTable_3.horizontalHeader().setCascadingSectionResizes(True)
        self.binaryPropTable_3.horizontalHeader().setMinimumSectionSize(100)
        self.binaryPropTable_3.horizontalHeader().setStretchLastSection(True)
        self.binaryPropTable_3.verticalHeader().setVisible(False)
        self.binaryPropTable_3.verticalHeader().setStretchLastSection(False)
        self.gridLayout_17.addWidget(self.binaryPropTable_3, 3, 1, 1, 1)
        self.browse_3 = QtWidgets.QPushButton(self.dpv_description_3)
        self.browse_3.setObjectName("browse_3")
        self.gridLayout_17.addWidget(self.browse_3, 2, 2, 1, 1)
        self.save_3 = QtWidgets.QPushButton(self.dpv_description_3)
        self.save_3.setAutoDefault(False)
        self.save_3.setDefault(True)
        self.save_3.setFlat(False)
        self.save_3.setObjectName("save_3")
        self.gridLayout_17.addWidget(self.save_3, 4, 2, 1, 1)
        self.delete_4 = QtWidgets.QPushButton(self.dpv_description_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_4.sizePolicy().hasHeightForWidth())
        self.delete_4.setSizePolicy(sizePolicy)
        self.delete_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.delete_4.setObjectName("delete_4")
        self.gridLayout_17.addWidget(self.delete_4, 4, 1, 1, 1)
        self.detailedProViewGrid_3.addWidget(self.dpv_description_3, 1, 0, 1, 1)
        self.boxGrid_3.addLayout(self.detailedProViewGrid_3, 0, 1, 1, 1)
        self.boxGrid_3.setColumnStretch(0, 2)
        self.boxGrid_3.setColumnStretch(1, 8)
        self.titleGrid_3.addLayout(self.boxGrid_3, 0, 0, 1, 1)
        self.mainGrid_3.addLayout(self.titleGrid_3, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.mainGrid_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.analysisTab, "")
        self.projectTab = QtWidgets.QWidget()
        self.projectTab.setAutoFillBackground(True)
        self.projectTab.setStyleSheet("")
        self.projectTab.setObjectName("projectTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.projectTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mainGrid = QtWidgets.QGridLayout()
        self.mainGrid.setObjectName("mainGrid")
        self.titleGrid = QtWidgets.QGridLayout()
        self.titleGrid.setObjectName("titleGrid")
        self.boxGrid = QtWidgets.QGridLayout()
        self.boxGrid.setObjectName("boxGrid")
        self.projectViewGrid = QtWidgets.QGridLayout()
        self.projectViewGrid.setObjectName("projectViewGrid")
        self.project_view = QtWidgets.QLabel(self.projectTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.project_view.setFont(font)
        self.project_view.setAutoFillBackground(False)
        self.project_view.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.project_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.project_view.setAlignment(QtCore.Qt.AlignCenter)
        self.project_view.setObjectName("project_view")
        self.projectViewGrid.addWidget(self.project_view, 0, 0, 1, 1)
        self.projViewBox = QtWidgets.QFrame(self.projectTab)
        self.projViewBox.setFrameShape(QtWidgets.QFrame.Panel)
        self.projViewBox.setObjectName("projViewBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.projViewBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_box = QtWidgets.QLineEdit(self.projViewBox)
        self.search_box.setText("")
        self.search_box.setClearButtonEnabled(True)
        self.search_box.setObjectName("search_box")
        self.verticalLayout.addWidget(self.search_box)
        self.existing_projects = QtWidgets.QListWidget(self.projViewBox)
        self.existing_projects.setAutoFillBackground(True)
        self.existing_projects.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.existing_projects.setObjectName("existing_projects")
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects.addItem(item)
        self.verticalLayout.addWidget(self.existing_projects)
        self.new_project = QtWidgets.QPushButton(self.projViewBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_project.sizePolicy().hasHeightForWidth())
        self.new_project.setSizePolicy(sizePolicy)
        self.new_project.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.new_project.setAutoFillBackground(False)
        self.new_project.setObjectName("new_project")
        self.verticalLayout.addWidget(self.new_project)
        self.gridLayout_10.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.projectViewGrid.addWidget(self.projViewBox, 1, 0, 1, 1)
        self.boxGrid.addLayout(self.projectViewGrid, 0, 0, 1, 1)
        self.detailedProViewGrid = QtWidgets.QGridLayout()
        self.detailedProViewGrid.setObjectName("detailedProViewGrid")
        self.DetailedProjectView = QtWidgets.QLabel(self.projectTab)
        self.DetailedProjectView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetailedProjectView.sizePolicy().hasHeightForWidth())
        self.DetailedProjectView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DetailedProjectView.setFont(font)
        self.DetailedProjectView.setAutoFillBackground(False)
        self.DetailedProjectView.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.DetailedProjectView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DetailedProjectView.setTextFormat(QtCore.Qt.RichText)
        self.DetailedProjectView.setAlignment(QtCore.Qt.AlignCenter)
        self.DetailedProjectView.setObjectName("DetailedProjectView")
        self.detailedProViewGrid.addWidget(self.DetailedProjectView, 0, 0, 1, 1)
        self.dpv_description = QtWidgets.QFrame(self.projectTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpv_description.sizePolicy().hasHeightForWidth())
        self.dpv_description.setSizePolicy(sizePolicy)
        self.dpv_description.setFrameShape(QtWidgets.QFrame.Box)
        self.dpv_description.setObjectName("dpv_description")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.dpv_description)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.binary_properties = QtWidgets.QLabel(self.dpv_description)
        self.binary_properties.setObjectName("binary_properties")
        self.gridLayout_15.addWidget(self.binary_properties, 3, 0, 1, 1)
        self.project_nameBox = QtWidgets.QLineEdit(self.dpv_description)
        self.project_nameBox.setObjectName("project_nameBox")
        self.gridLayout_15.addWidget(self.project_nameBox, 0, 1, 1, 1)
        self.project_name = QtWidgets.QLabel(self.dpv_description)
        self.project_name.setObjectName("project_name")
        self.gridLayout_15.addWidget(self.project_name, 0, 0, 1, 1)
        self.project_description = QtWidgets.QLabel(self.dpv_description)
        self.project_description.setObjectName("project_description")
        self.gridLayout_15.addWidget(self.project_description, 1, 0, 1, 1)
        self.filePathBox = QtWidgets.QLineEdit(self.dpv_description)
        self.filePathBox.setObjectName("filePathBox")
        self.gridLayout_15.addWidget(self.filePathBox, 2, 1, 1, 1)
        self.description_box = QtWidgets.QTextEdit(self.dpv_description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_box.sizePolicy().hasHeightForWidth())
        self.description_box.setSizePolicy(sizePolicy)
        self.description_box.setObjectName("description_box")
        self.gridLayout_15.addWidget(self.description_box, 1, 1, 1, 1)
        self.browse = QtWidgets.QPushButton(self.dpv_description)
        self.browse.setObjectName("browse")
        self.gridLayout_15.addWidget(self.browse, 2, 2, 1, 1)
        self.save = QtWidgets.QPushButton(self.dpv_description)
        self.save.setAutoDefault(False)
        self.save.setDefault(True)
        self.save.setFlat(False)
        self.save.setObjectName("save")
        self.gridLayout_15.addWidget(self.save, 4, 2, 1, 1)
        self.delete_2 = QtWidgets.QPushButton(self.dpv_description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_2.sizePolicy().hasHeightForWidth())
        self.delete_2.setSizePolicy(sizePolicy)
        self.delete_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.delete_2.setObjectName("delete_2")
        self.gridLayout_15.addWidget(self.delete_2, 4, 1, 1, 1)
        self.file_path = QtWidgets.QLabel(self.dpv_description)
        self.file_path.setObjectName("file_path")
        self.gridLayout_15.addWidget(self.file_path, 2, 0, 1, 1)
        self.binaryPropTable = QtWidgets.QTableWidget(self.dpv_description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.binaryPropTable.sizePolicy().hasHeightForWidth())
        self.binaryPropTable.setSizePolicy(sizePolicy)
        self.binaryPropTable.setMaximumSize(QtCore.QSize(346, 16777215))
        self.binaryPropTable.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.binaryPropTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.binaryPropTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.binaryPropTable.setAlternatingRowColors(True)
        self.binaryPropTable.setShowGrid(True)
        self.binaryPropTable.setWordWrap(False)
        self.binaryPropTable.setObjectName("binaryPropTable")
        self.binaryPropTable.setColumnCount(2)
        self.binaryPropTable.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable.setItem(12, 0, item)
        self.binaryPropTable.horizontalHeader().setVisible(False)
        self.binaryPropTable.horizontalHeader().setCascadingSectionResizes(True)
        self.binaryPropTable.horizontalHeader().setMinimumSectionSize(100)
        self.binaryPropTable.horizontalHeader().setStretchLastSection(True)
        self.binaryPropTable.verticalHeader().setVisible(False)
        self.binaryPropTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_15.addWidget(self.binaryPropTable, 3, 1, 1, 1)
        self.detailedProViewGrid.addWidget(self.dpv_description, 1, 0, 1, 1)
        self.boxGrid.addLayout(self.detailedProViewGrid, 0, 1, 1, 1)
        self.boxGrid.setColumnStretch(0, 2)
        self.boxGrid.setColumnStretch(1, 8)
        self.titleGrid.addLayout(self.boxGrid, 0, 0, 1, 1)
        self.mainGrid.addLayout(self.titleGrid, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.mainGrid, 0, 0, 1, 1)
        self.tabWidget.addTab(self.projectTab, "")
        self.pluginTab = QtWidgets.QWidget()
        self.pluginTab.setObjectName("pluginTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pluginTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mainGrid_2 = QtWidgets.QGridLayout()
        self.mainGrid_2.setObjectName("mainGrid_2")
        self.titleGrid_2 = QtWidgets.QGridLayout()
        self.titleGrid_2.setObjectName("titleGrid_2")
        self.boxGrid_2 = QtWidgets.QGridLayout()
        self.boxGrid_2.setObjectName("boxGrid_2")
        self.projectViewGrid_2 = QtWidgets.QGridLayout()
        self.projectViewGrid_2.setObjectName("projectViewGrid_2")
        self.project_view_2 = QtWidgets.QLabel(self.pluginTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.project_view_2.setFont(font)
        self.project_view_2.setAutoFillBackground(False)
        self.project_view_2.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.project_view_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.project_view_2.setAlignment(QtCore.Qt.AlignCenter)
        self.project_view_2.setObjectName("project_view_2")
        self.projectViewGrid_2.addWidget(self.project_view_2, 0, 0, 1, 1)
        self.projViewBox_2 = QtWidgets.QFrame(self.pluginTab)
        self.projViewBox_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.projViewBox_2.setObjectName("projViewBox_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.projViewBox_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_box_2 = QtWidgets.QLineEdit(self.projViewBox_2)
        self.search_box_2.setText("")
        self.search_box_2.setClearButtonEnabled(True)
        self.search_box_2.setObjectName("search_box_2")
        self.verticalLayout_2.addWidget(self.search_box_2)
        self.existing_projects_2 = QtWidgets.QListWidget(self.projViewBox_2)
        self.existing_projects_2.setAutoFillBackground(True)
        self.existing_projects_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.existing_projects_2.setObjectName("existing_projects_2")
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_2.addItem(item)
        self.verticalLayout_2.addWidget(self.existing_projects_2)
        self.new_project_2 = QtWidgets.QPushButton(self.projViewBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_project_2.sizePolicy().hasHeightForWidth())
        self.new_project_2.setSizePolicy(sizePolicy)
        self.new_project_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.new_project_2.setAutoFillBackground(False)
        self.new_project_2.setObjectName("new_project_2")
        self.verticalLayout_2.addWidget(self.new_project_2)
        self.gridLayout_11.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.projectViewGrid_2.addWidget(self.projViewBox_2, 1, 0, 1, 1)
        self.boxGrid_2.addLayout(self.projectViewGrid_2, 0, 0, 1, 1)
        self.detailedProViewGrid_2 = QtWidgets.QGridLayout()
        self.detailedProViewGrid_2.setObjectName("detailedProViewGrid_2")
        self.DetailedProjectView_2 = QtWidgets.QLabel(self.pluginTab)
        self.DetailedProjectView_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetailedProjectView_2.sizePolicy().hasHeightForWidth())
        self.DetailedProjectView_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DetailedProjectView_2.setFont(font)
        self.DetailedProjectView_2.setAutoFillBackground(False)
        self.DetailedProjectView_2.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.DetailedProjectView_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DetailedProjectView_2.setTextFormat(QtCore.Qt.RichText)
        self.DetailedProjectView_2.setAlignment(QtCore.Qt.AlignCenter)
        self.DetailedProjectView_2.setObjectName("DetailedProjectView_2")
        self.detailedProViewGrid_2.addWidget(self.DetailedProjectView_2, 0, 0, 1, 1)
        self.dpv_description_2 = QtWidgets.QFrame(self.pluginTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpv_description_2.sizePolicy().hasHeightForWidth())
        self.dpv_description_2.setSizePolicy(sizePolicy)
        self.dpv_description_2.setFrameShape(QtWidgets.QFrame.Box)
        self.dpv_description_2.setObjectName("dpv_description_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.dpv_description_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_3 = QtWidgets.QLabel(self.dpv_description_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_16.addWidget(self.label_3, 5, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.dpv_description_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_16.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.file_path_2 = QtWidgets.QLabel(self.dpv_description_2)
        self.file_path_2.setObjectName("file_path_2")
        self.gridLayout_16.addWidget(self.file_path_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.dpv_description_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_16.addWidget(self.label_4, 3, 0, 1, 1)
        self.project_nameBox_2 = QtWidgets.QLineEdit(self.dpv_description_2)
        self.project_nameBox_2.setObjectName("project_nameBox_2")
        self.gridLayout_16.addWidget(self.project_nameBox_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem, 7, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem1, 9, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.dpv_description_2)
        self.label.setObjectName("label")
        self.gridLayout_16.addWidget(self.label, 1, 0, 1, 1)
        self.project_name_2 = QtWidgets.QLabel(self.dpv_description_2)
        self.project_name_2.setObjectName("project_name_2")
        self.gridLayout_16.addWidget(self.project_name_2, 0, 0, 1, 1)
        self.filePathBox_2 = QtWidgets.QLineEdit(self.dpv_description_2)
        self.filePathBox_2.setObjectName("filePathBox_2")
        self.gridLayout_16.addWidget(self.filePathBox_2, 2, 1, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.dpv_description_2)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_16.addWidget(self.textEdit_2, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem2, 8, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.dpv_description_2)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_16.addWidget(self.comboBox, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.dpv_description_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_16.addWidget(self.pushButton, 1, 2, 1, 1)
        self.save_2 = QtWidgets.QPushButton(self.dpv_description_2)
        self.save_2.setAutoDefault(False)
        self.save_2.setDefault(True)
        self.save_2.setFlat(False)
        self.save_2.setObjectName("save_2")
        self.gridLayout_16.addWidget(self.save_2, 10, 2, 1, 1)
        self.delete_3 = QtWidgets.QPushButton(self.dpv_description_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_3.sizePolicy().hasHeightForWidth())
        self.delete_3.setSizePolicy(sizePolicy)
        self.delete_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.delete_3.setObjectName("delete_3")
        self.gridLayout_16.addWidget(self.delete_3, 10, 0, 1, 1)
        self.browse_2 = QtWidgets.QPushButton(self.dpv_description_2)
        self.browse_2.setObjectName("browse_2")
        self.gridLayout_16.addWidget(self.browse_2, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dpv_description_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_16.addWidget(self.label_2, 4, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.dpv_description_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_16.addWidget(self.textEdit, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem3, 6, 1, 1, 1)
        self.detailedProViewGrid_2.addWidget(self.dpv_description_2, 1, 0, 1, 1)
        self.boxGrid_2.addLayout(self.detailedProViewGrid_2, 0, 1, 1, 1)
        self.boxGrid_2.setColumnStretch(0, 2)
        self.boxGrid_2.setColumnStretch(1, 8)
        self.titleGrid_2.addLayout(self.boxGrid_2, 0, 0, 1, 1)
        self.mainGrid_2.addLayout(self.titleGrid_2, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.mainGrid_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pluginTab, "")
        self.PoiTab = QtWidgets.QWidget()
        self.PoiTab.setObjectName("PoiTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.PoiTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mainGrid_4 = QtWidgets.QGridLayout()
        self.mainGrid_4.setObjectName("mainGrid_4")
        self.titleGrid_4 = QtWidgets.QGridLayout()
        self.titleGrid_4.setObjectName("titleGrid_4")
        self.boxGrid_4 = QtWidgets.QGridLayout()
        self.boxGrid_4.setObjectName("boxGrid_4")
        self.projectViewGrid_4 = QtWidgets.QGridLayout()
        self.projectViewGrid_4.setObjectName("projectViewGrid_4")
        self.project_view_4 = QtWidgets.QLabel(self.PoiTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.project_view_4.setFont(font)
        self.project_view_4.setAutoFillBackground(False)
        self.project_view_4.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.project_view_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.project_view_4.setAlignment(QtCore.Qt.AlignCenter)
        self.project_view_4.setObjectName("project_view_4")
        self.projectViewGrid_4.addWidget(self.project_view_4, 0, 0, 1, 1)
        self.projViewBox_4 = QtWidgets.QFrame(self.PoiTab)
        self.projViewBox_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.projViewBox_4.setObjectName("projViewBox_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.projViewBox_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.search_box_4 = QtWidgets.QLineEdit(self.projViewBox_4)
        self.search_box_4.setText("")
        self.search_box_4.setClearButtonEnabled(True)
        self.search_box_4.setObjectName("search_box_4")
        self.verticalLayout_4.addWidget(self.search_box_4)
        self.existing_projects_4 = QtWidgets.QListWidget(self.projViewBox_4)
        self.existing_projects_4.setAutoFillBackground(True)
        self.existing_projects_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.existing_projects_4.setObjectName("existing_projects_4")
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_4.addItem(item)
        self.verticalLayout_4.addWidget(self.existing_projects_4)
        self.new_project_4 = QtWidgets.QPushButton(self.projViewBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_project_4.sizePolicy().hasHeightForWidth())
        self.new_project_4.setSizePolicy(sizePolicy)
        self.new_project_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.new_project_4.setAutoFillBackground(False)
        self.new_project_4.setObjectName("new_project_4")
        self.verticalLayout_4.addWidget(self.new_project_4)
        self.gridLayout_13.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.projectViewGrid_4.addWidget(self.projViewBox_4, 1, 0, 1, 1)
        self.boxGrid_4.addLayout(self.projectViewGrid_4, 0, 0, 1, 1)
        self.detailedProViewGrid_4 = QtWidgets.QGridLayout()
        self.detailedProViewGrid_4.setObjectName("detailedProViewGrid_4")
        self.DetailedProjectView_4 = QtWidgets.QLabel(self.PoiTab)
        self.DetailedProjectView_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetailedProjectView_4.sizePolicy().hasHeightForWidth())
        self.DetailedProjectView_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DetailedProjectView_4.setFont(font)
        self.DetailedProjectView_4.setAutoFillBackground(False)
        self.DetailedProjectView_4.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.DetailedProjectView_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DetailedProjectView_4.setTextFormat(QtCore.Qt.RichText)
        self.DetailedProjectView_4.setAlignment(QtCore.Qt.AlignCenter)
        self.DetailedProjectView_4.setObjectName("DetailedProjectView_4")
        self.detailedProViewGrid_4.addWidget(self.DetailedProjectView_4, 0, 0, 1, 1)
        self.dpv_description_4 = QtWidgets.QFrame(self.PoiTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpv_description_4.sizePolicy().hasHeightForWidth())
        self.dpv_description_4.setSizePolicy(sizePolicy)
        self.dpv_description_4.setFrameShape(QtWidgets.QFrame.Box)
        self.dpv_description_4.setObjectName("dpv_description_4")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.dpv_description_4)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.binary_properties_4 = QtWidgets.QLabel(self.dpv_description_4)
        self.binary_properties_4.setObjectName("binary_properties_4")
        self.gridLayout_18.addWidget(self.binary_properties_4, 3, 0, 1, 1)
        self.project_nameBox_4 = QtWidgets.QLineEdit(self.dpv_description_4)
        self.project_nameBox_4.setObjectName("project_nameBox_4")
        self.gridLayout_18.addWidget(self.project_nameBox_4, 0, 1, 1, 1)
        self.project_name_4 = QtWidgets.QLabel(self.dpv_description_4)
        self.project_name_4.setObjectName("project_name_4")
        self.gridLayout_18.addWidget(self.project_name_4, 0, 0, 1, 1)
        self.project_description_4 = QtWidgets.QLabel(self.dpv_description_4)
        self.project_description_4.setObjectName("project_description_4")
        self.gridLayout_18.addWidget(self.project_description_4, 1, 0, 1, 1)
        self.filePathBox_4 = QtWidgets.QLineEdit(self.dpv_description_4)
        self.filePathBox_4.setObjectName("filePathBox_4")
        self.gridLayout_18.addWidget(self.filePathBox_4, 2, 1, 1, 1)
        self.description_box_4 = QtWidgets.QTextEdit(self.dpv_description_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_box_4.sizePolicy().hasHeightForWidth())
        self.description_box_4.setSizePolicy(sizePolicy)
        self.description_box_4.setObjectName("description_box_4")
        self.gridLayout_18.addWidget(self.description_box_4, 1, 1, 1, 1)
        self.browse_4 = QtWidgets.QPushButton(self.dpv_description_4)
        self.browse_4.setObjectName("browse_4")
        self.gridLayout_18.addWidget(self.browse_4, 2, 2, 1, 1)
        self.save_4 = QtWidgets.QPushButton(self.dpv_description_4)
        self.save_4.setAutoDefault(False)
        self.save_4.setDefault(True)
        self.save_4.setFlat(False)
        self.save_4.setObjectName("save_4")
        self.gridLayout_18.addWidget(self.save_4, 4, 2, 1, 1)
        self.delete_5 = QtWidgets.QPushButton(self.dpv_description_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_5.sizePolicy().hasHeightForWidth())
        self.delete_5.setSizePolicy(sizePolicy)
        self.delete_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.delete_5.setObjectName("delete_5")
        self.gridLayout_18.addWidget(self.delete_5, 4, 1, 1, 1)
        self.file_path_4 = QtWidgets.QLabel(self.dpv_description_4)
        self.file_path_4.setObjectName("file_path_4")
        self.gridLayout_18.addWidget(self.file_path_4, 2, 0, 1, 1)
        self.binaryPropTable_4 = QtWidgets.QTableWidget(self.dpv_description_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.binaryPropTable_4.sizePolicy().hasHeightForWidth())
        self.binaryPropTable_4.setSizePolicy(sizePolicy)
        self.binaryPropTable_4.setMaximumSize(QtCore.QSize(346, 16777215))
        self.binaryPropTable_4.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.binaryPropTable_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.binaryPropTable_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.binaryPropTable_4.setAlternatingRowColors(True)
        self.binaryPropTable_4.setShowGrid(True)
        self.binaryPropTable_4.setWordWrap(False)
        self.binaryPropTable_4.setObjectName("binaryPropTable_4")
        self.binaryPropTable_4.setColumnCount(2)
        self.binaryPropTable_4.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_4.setItem(12, 0, item)
        self.binaryPropTable_4.horizontalHeader().setVisible(False)
        self.binaryPropTable_4.horizontalHeader().setCascadingSectionResizes(True)
        self.binaryPropTable_4.horizontalHeader().setMinimumSectionSize(100)
        self.binaryPropTable_4.horizontalHeader().setStretchLastSection(True)
        self.binaryPropTable_4.verticalHeader().setVisible(False)
        self.binaryPropTable_4.verticalHeader().setStretchLastSection(False)
        self.gridLayout_18.addWidget(self.binaryPropTable_4, 3, 1, 1, 1)
        self.detailedProViewGrid_4.addWidget(self.dpv_description_4, 1, 0, 1, 1)
        self.boxGrid_4.addLayout(self.detailedProViewGrid_4, 0, 1, 1, 1)
        self.boxGrid_4.setColumnStretch(0, 2)
        self.boxGrid_4.setColumnStretch(1, 8)
        self.titleGrid_4.addLayout(self.boxGrid_4, 0, 0, 1, 1)
        self.mainGrid_4.addLayout(self.titleGrid_4, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.mainGrid_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.PoiTab, "")
        self.documentationTab = QtWidgets.QWidget()
        self.documentationTab.setObjectName("documentationTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.documentationTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.mainGrid_5 = QtWidgets.QGridLayout()
        self.mainGrid_5.setObjectName("mainGrid_5")
        self.titleGrid_5 = QtWidgets.QGridLayout()
        self.titleGrid_5.setObjectName("titleGrid_5")
        self.boxGrid_5 = QtWidgets.QGridLayout()
        self.boxGrid_5.setObjectName("boxGrid_5")
        self.projectViewGrid_5 = QtWidgets.QGridLayout()
        self.projectViewGrid_5.setObjectName("projectViewGrid_5")
        self.project_view_5 = QtWidgets.QLabel(self.documentationTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.project_view_5.setFont(font)
        self.project_view_5.setAutoFillBackground(False)
        self.project_view_5.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.project_view_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.project_view_5.setAlignment(QtCore.Qt.AlignCenter)
        self.project_view_5.setObjectName("project_view_5")
        self.projectViewGrid_5.addWidget(self.project_view_5, 0, 0, 1, 1)
        self.projViewBox_5 = QtWidgets.QFrame(self.documentationTab)
        self.projViewBox_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.projViewBox_5.setObjectName("projViewBox_5")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.projViewBox_5)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.search_box_5 = QtWidgets.QLineEdit(self.projViewBox_5)
        self.search_box_5.setText("")
        self.search_box_5.setClearButtonEnabled(True)
        self.search_box_5.setObjectName("search_box_5")
        self.verticalLayout_5.addWidget(self.search_box_5)
        self.existing_projects_5 = QtWidgets.QListWidget(self.projViewBox_5)
        self.existing_projects_5.setAutoFillBackground(True)
        self.existing_projects_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.existing_projects_5.setObjectName("existing_projects_5")
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.existing_projects_5.addItem(item)
        self.verticalLayout_5.addWidget(self.existing_projects_5)
        self.new_project_5 = QtWidgets.QPushButton(self.projViewBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_project_5.sizePolicy().hasHeightForWidth())
        self.new_project_5.setSizePolicy(sizePolicy)
        self.new_project_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.new_project_5.setAutoFillBackground(False)
        self.new_project_5.setObjectName("new_project_5")
        self.verticalLayout_5.addWidget(self.new_project_5)
        self.gridLayout_14.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.projectViewGrid_5.addWidget(self.projViewBox_5, 1, 0, 1, 1)
        self.boxGrid_5.addLayout(self.projectViewGrid_5, 0, 0, 1, 1)
        self.detailedProViewGrid_5 = QtWidgets.QGridLayout()
        self.detailedProViewGrid_5.setObjectName("detailedProViewGrid_5")
        self.DetailedProjectView_5 = QtWidgets.QLabel(self.documentationTab)
        self.DetailedProjectView_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetailedProjectView_5.sizePolicy().hasHeightForWidth())
        self.DetailedProjectView_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DetailedProjectView_5.setFont(font)
        self.DetailedProjectView_5.setAutoFillBackground(False)
        self.DetailedProjectView_5.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.DetailedProjectView_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DetailedProjectView_5.setTextFormat(QtCore.Qt.RichText)
        self.DetailedProjectView_5.setAlignment(QtCore.Qt.AlignCenter)
        self.DetailedProjectView_5.setObjectName("DetailedProjectView_5")
        self.detailedProViewGrid_5.addWidget(self.DetailedProjectView_5, 0, 0, 1, 1)
        self.dpv_description_5 = QtWidgets.QFrame(self.documentationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dpv_description_5.sizePolicy().hasHeightForWidth())
        self.dpv_description_5.setSizePolicy(sizePolicy)
        self.dpv_description_5.setFrameShape(QtWidgets.QFrame.Box)
        self.dpv_description_5.setObjectName("dpv_description_5")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.dpv_description_5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.binary_properties_5 = QtWidgets.QLabel(self.dpv_description_5)
        self.binary_properties_5.setObjectName("binary_properties_5")
        self.gridLayout_19.addWidget(self.binary_properties_5, 3, 0, 1, 1)
        self.project_nameBox_5 = QtWidgets.QLineEdit(self.dpv_description_5)
        self.project_nameBox_5.setObjectName("project_nameBox_5")
        self.gridLayout_19.addWidget(self.project_nameBox_5, 0, 1, 1, 1)
        self.project_name_5 = QtWidgets.QLabel(self.dpv_description_5)
        self.project_name_5.setObjectName("project_name_5")
        self.gridLayout_19.addWidget(self.project_name_5, 0, 0, 1, 1)
        self.project_description_5 = QtWidgets.QLabel(self.dpv_description_5)
        self.project_description_5.setObjectName("project_description_5")
        self.gridLayout_19.addWidget(self.project_description_5, 1, 0, 1, 1)
        self.filePathBox_5 = QtWidgets.QLineEdit(self.dpv_description_5)
        self.filePathBox_5.setObjectName("filePathBox_5")
        self.gridLayout_19.addWidget(self.filePathBox_5, 2, 1, 1, 1)
        self.description_box_5 = QtWidgets.QTextEdit(self.dpv_description_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_box_5.sizePolicy().hasHeightForWidth())
        self.description_box_5.setSizePolicy(sizePolicy)
        self.description_box_5.setObjectName("description_box_5")
        self.gridLayout_19.addWidget(self.description_box_5, 1, 1, 1, 1)
        self.browse_5 = QtWidgets.QPushButton(self.dpv_description_5)
        self.browse_5.setObjectName("browse_5")
        self.gridLayout_19.addWidget(self.browse_5, 2, 2, 1, 1)
        self.save_5 = QtWidgets.QPushButton(self.dpv_description_5)
        self.save_5.setAutoDefault(False)
        self.save_5.setDefault(True)
        self.save_5.setFlat(False)
        self.save_5.setObjectName("save_5")
        self.gridLayout_19.addWidget(self.save_5, 4, 2, 1, 1)
        self.delete_6 = QtWidgets.QPushButton(self.dpv_description_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_6.sizePolicy().hasHeightForWidth())
        self.delete_6.setSizePolicy(sizePolicy)
        self.delete_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.delete_6.setObjectName("delete_6")
        self.gridLayout_19.addWidget(self.delete_6, 4, 1, 1, 1)
        self.file_path_5 = QtWidgets.QLabel(self.dpv_description_5)
        self.file_path_5.setObjectName("file_path_5")
        self.gridLayout_19.addWidget(self.file_path_5, 2, 0, 1, 1)
        self.binaryPropTable_5 = QtWidgets.QTableWidget(self.dpv_description_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.binaryPropTable_5.sizePolicy().hasHeightForWidth())
        self.binaryPropTable_5.setSizePolicy(sizePolicy)
        self.binaryPropTable_5.setMaximumSize(QtCore.QSize(346, 16777215))
        self.binaryPropTable_5.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.binaryPropTable_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.binaryPropTable_5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.binaryPropTable_5.setAlternatingRowColors(True)
        self.binaryPropTable_5.setShowGrid(True)
        self.binaryPropTable_5.setWordWrap(False)
        self.binaryPropTable_5.setObjectName("binaryPropTable_5")
        self.binaryPropTable_5.setColumnCount(2)
        self.binaryPropTable_5.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.binaryPropTable_5.setItem(12, 0, item)
        self.binaryPropTable_5.horizontalHeader().setVisible(False)
        self.binaryPropTable_5.horizontalHeader().setCascadingSectionResizes(True)
        self.binaryPropTable_5.horizontalHeader().setMinimumSectionSize(100)
        self.binaryPropTable_5.horizontalHeader().setStretchLastSection(True)
        self.binaryPropTable_5.verticalHeader().setVisible(False)
        self.binaryPropTable_5.verticalHeader().setStretchLastSection(False)
        self.gridLayout_19.addWidget(self.binaryPropTable_5, 3, 1, 1, 1)
        self.detailedProViewGrid_5.addWidget(self.dpv_description_5, 1, 0, 1, 1)
        self.boxGrid_5.addLayout(self.detailedProViewGrid_5, 0, 1, 1, 1)
        self.boxGrid_5.setColumnStretch(0, 2)
        self.boxGrid_5.setColumnStretch(1, 8)
        self.titleGrid_5.addLayout(self.boxGrid_5, 0, 0, 1, 1)
        self.mainGrid_5.addLayout(self.titleGrid_5, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.mainGrid_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.documentationTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.existing_projects_3.setCurrentRow(-1)
        self.existing_projects.setCurrentRow(-1)
        self.existing_projects_2.setCurrentRow(-1)
        self.existing_projects_4.setCurrentRow(-1)
        self.existing_projects_5.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BEAT: Behavior Extraction and Analysis Tool"))
        self.project_view_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Project View</span></p></body></html>"))
        self.search_box_3.setPlaceholderText(_translate("MainWindow", "Search Project"))
        self.existing_projects_3.setSortingEnabled(False)
        __sortingEnabled = self.existing_projects_3.isSortingEnabled()
        self.existing_projects_3.setSortingEnabled(False)
        item = self.existing_projects_3.item(0)
        item.setText(_translate("MainWindow", "Project A"))
        item = self.existing_projects_3.item(1)
        item.setText(_translate("MainWindow", "Project B"))
        item = self.existing_projects_3.item(2)
        item.setText(_translate("MainWindow", "Project C"))
        item = self.existing_projects_3.item(3)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_3.item(4)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_3.item(5)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_3.item(6)
        item.setText(_translate("MainWindow", "Project X"))
        self.existing_projects_3.setSortingEnabled(__sortingEnabled)
        self.new_project_3.setText(_translate("MainWindow", "New"))
        self.DetailedProjectView_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Project View</span></p></body></html>"))
        self.project_name_3.setText(_translate("MainWindow", "Project Name"))
        self.file_path_3.setText(_translate("MainWindow", "Binary File Path"))
        self.binary_properties_3.setText(_translate("MainWindow", "Binary File \n"
"Properties"))
        self.project_description_3.setText(_translate("MainWindow", "Project \n"
"Description"))
        item = self.binaryPropTable_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.binaryPropTable_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.binaryPropTable_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.binaryPropTable_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.binaryPropTable_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.binaryPropTable_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.binaryPropTable_3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.binaryPropTable_3.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.binaryPropTable_3.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.binaryPropTable_3.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.binaryPropTable_3.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.binaryPropTable_3.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.binaryPropTable_3.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.binaryPropTable_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.binaryPropTable_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.binaryPropTable_3.isSortingEnabled()
        self.binaryPropTable_3.setSortingEnabled(False)
        item = self.binaryPropTable_3.item(0, 0)
        item.setText(_translate("MainWindow", "OS"))
        item = self.binaryPropTable_3.item(1, 0)
        item.setText(_translate("MainWindow", "Binary Type"))
        item = self.binaryPropTable_3.item(2, 0)
        item.setText(_translate("MainWindow", "Machine"))
        item = self.binaryPropTable_3.item(3, 0)
        item.setText(_translate("MainWindow", "Class"))
        item = self.binaryPropTable_3.item(4, 0)
        item.setText(_translate("MainWindow", "Bits"))
        item = self.binaryPropTable_3.item(5, 0)
        item.setText(_translate("MainWindow", "Language"))
        item = self.binaryPropTable_3.item(6, 0)
        item.setText(_translate("MainWindow", "Canary"))
        item = self.binaryPropTable_3.item(7, 0)
        item.setText(_translate("MainWindow", "Crypto"))
        item = self.binaryPropTable_3.item(8, 0)
        item.setText(_translate("MainWindow", "Nx"))
        item = self.binaryPropTable_3.item(9, 0)
        item.setText(_translate("MainWindow", "Pic"))
        item = self.binaryPropTable_3.item(10, 0)
        item.setText(_translate("MainWindow", "Relocs"))
        item = self.binaryPropTable_3.item(11, 0)
        item.setText(_translate("MainWindow", "Relro"))
        item = self.binaryPropTable_3.item(12, 0)
        item.setText(_translate("MainWindow", "Stripped"))
        self.binaryPropTable_3.setSortingEnabled(__sortingEnabled)
        self.browse_3.setText(_translate("MainWindow", "Browse"))
        self.save_3.setText(_translate("MainWindow", "Save"))
        self.delete_4.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysisTab), _translate("MainWindow", "Analysis "))
        self.project_view.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Project View</span></p></body></html>"))
        self.search_box.setPlaceholderText(_translate("MainWindow", "Search Project"))
        self.existing_projects.setSortingEnabled(False)
        __sortingEnabled = self.existing_projects.isSortingEnabled()
        self.existing_projects.setSortingEnabled(False)
        item = self.existing_projects.item(0)
        item.setText(_translate("MainWindow", "Project A"))
        item = self.existing_projects.item(1)
        item.setText(_translate("MainWindow", "Project B"))
        item = self.existing_projects.item(2)
        item.setText(_translate("MainWindow", "Project C"))
        item = self.existing_projects.item(3)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects.item(4)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects.item(5)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects.item(6)
        item.setText(_translate("MainWindow", "Project X"))
        self.existing_projects.setSortingEnabled(__sortingEnabled)
        self.new_project.setText(_translate("MainWindow", "New"))
        self.DetailedProjectView.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Project View</span></p></body></html>"))
        self.binary_properties.setText(_translate("MainWindow", "Binary File \n"
"Properties"))
        self.project_name.setText(_translate("MainWindow", "Project Name"))
        self.project_description.setText(_translate("MainWindow", "Project \n"
"Description"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.delete_2.setText(_translate("MainWindow", "Delete"))
        self.file_path.setText(_translate("MainWindow", "Binary File Path"))
        item = self.binaryPropTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.binaryPropTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.binaryPropTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.binaryPropTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.binaryPropTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.binaryPropTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.binaryPropTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.binaryPropTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.binaryPropTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.binaryPropTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.binaryPropTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.binaryPropTable.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.binaryPropTable.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.binaryPropTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.binaryPropTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.binaryPropTable.isSortingEnabled()
        self.binaryPropTable.setSortingEnabled(False)
        item = self.binaryPropTable.item(0, 0)
        item.setText(_translate("MainWindow", "OS"))
        item = self.binaryPropTable.item(1, 0)
        item.setText(_translate("MainWindow", "Binary Type"))
        item = self.binaryPropTable.item(2, 0)
        item.setText(_translate("MainWindow", "Machine"))
        item = self.binaryPropTable.item(3, 0)
        item.setText(_translate("MainWindow", "Class"))
        item = self.binaryPropTable.item(4, 0)
        item.setText(_translate("MainWindow", "Bits"))
        item = self.binaryPropTable.item(5, 0)
        item.setText(_translate("MainWindow", "Language"))
        item = self.binaryPropTable.item(6, 0)
        item.setText(_translate("MainWindow", "Canary"))
        item = self.binaryPropTable.item(7, 0)
        item.setText(_translate("MainWindow", "Crypto"))
        item = self.binaryPropTable.item(8, 0)
        item.setText(_translate("MainWindow", "Nx"))
        item = self.binaryPropTable.item(9, 0)
        item.setText(_translate("MainWindow", "Pic"))
        item = self.binaryPropTable.item(10, 0)
        item.setText(_translate("MainWindow", "Relocs"))
        item = self.binaryPropTable.item(11, 0)
        item.setText(_translate("MainWindow", "Relro"))
        item = self.binaryPropTable.item(12, 0)
        item.setText(_translate("MainWindow", "Stripped"))
        self.binaryPropTable.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("MainWindow", "Project"))
        self.project_view_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Plugin View</span></p></body></html>"))
        self.search_box_2.setPlaceholderText(_translate("MainWindow", "Search Project"))
        self.existing_projects_2.setSortingEnabled(False)
        __sortingEnabled = self.existing_projects_2.isSortingEnabled()
        self.existing_projects_2.setSortingEnabled(False)
        item = self.existing_projects_2.item(0)
        item.setText(_translate("MainWindow", "Plugin A"))
        item = self.existing_projects_2.item(1)
        item.setText(_translate("MainWindow", "Plugin B"))
        item = self.existing_projects_2.item(2)
        item.setText(_translate("MainWindow", "Plugin C"))
        item = self.existing_projects_2.item(3)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_2.item(4)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_2.item(5)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_2.item(6)
        item.setText(_translate("MainWindow", "Plugin X"))
        self.existing_projects_2.setSortingEnabled(__sortingEnabled)
        self.new_project_2.setText(_translate("MainWindow", "New"))
        self.DetailedProjectView_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Plugin View</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Points of Interest"))
        self.file_path_2.setText(_translate("MainWindow", "Plugin Name"))
        self.label_4.setText(_translate("MainWindow", "Plugin Description"))
        self.label.setText(_translate("MainWindow", "Plugin Predefined Data Set"))
        self.project_name_2.setText(_translate("MainWindow", "Plugin Structure"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.save_2.setText(_translate("MainWindow", "Save"))
        self.delete_3.setText(_translate("MainWindow", "Delete"))
        self.browse_2.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Default Output Field"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pluginTab), _translate("MainWindow", "Plugin Management"))
        self.project_view_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Project View</span></p></body></html>"))
        self.search_box_4.setPlaceholderText(_translate("MainWindow", "Search Project"))
        self.existing_projects_4.setSortingEnabled(False)
        __sortingEnabled = self.existing_projects_4.isSortingEnabled()
        self.existing_projects_4.setSortingEnabled(False)
        item = self.existing_projects_4.item(0)
        item.setText(_translate("MainWindow", "Project A"))
        item = self.existing_projects_4.item(1)
        item.setText(_translate("MainWindow", "Project B"))
        item = self.existing_projects_4.item(2)
        item.setText(_translate("MainWindow", "Project C"))
        item = self.existing_projects_4.item(3)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_4.item(4)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_4.item(5)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_4.item(6)
        item.setText(_translate("MainWindow", "Project X"))
        self.existing_projects_4.setSortingEnabled(__sortingEnabled)
        self.new_project_4.setText(_translate("MainWindow", "New"))
        self.DetailedProjectView_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Project View</span></p></body></html>"))
        self.binary_properties_4.setText(_translate("MainWindow", "Binary File \n"
"Properties"))
        self.project_name_4.setText(_translate("MainWindow", "Project Name"))
        self.project_description_4.setText(_translate("MainWindow", "Project \n"
"Description"))
        self.browse_4.setText(_translate("MainWindow", "Browse"))
        self.save_4.setText(_translate("MainWindow", "Save"))
        self.delete_5.setText(_translate("MainWindow", "Delete"))
        self.file_path_4.setText(_translate("MainWindow", "Binary File Path"))
        item = self.binaryPropTable_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.binaryPropTable_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.binaryPropTable_4.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.binaryPropTable_4.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.binaryPropTable_4.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.binaryPropTable_4.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.binaryPropTable_4.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.binaryPropTable_4.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.binaryPropTable_4.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.binaryPropTable_4.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.binaryPropTable_4.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.binaryPropTable_4.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.binaryPropTable_4.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.binaryPropTable_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.binaryPropTable_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.binaryPropTable_4.isSortingEnabled()
        self.binaryPropTable_4.setSortingEnabled(False)
        item = self.binaryPropTable_4.item(0, 0)
        item.setText(_translate("MainWindow", "OS"))
        item = self.binaryPropTable_4.item(1, 0)
        item.setText(_translate("MainWindow", "Binary Type"))
        item = self.binaryPropTable_4.item(2, 0)
        item.setText(_translate("MainWindow", "Machine"))
        item = self.binaryPropTable_4.item(3, 0)
        item.setText(_translate("MainWindow", "Class"))
        item = self.binaryPropTable_4.item(4, 0)
        item.setText(_translate("MainWindow", "Bits"))
        item = self.binaryPropTable_4.item(5, 0)
        item.setText(_translate("MainWindow", "Language"))
        item = self.binaryPropTable_4.item(6, 0)
        item.setText(_translate("MainWindow", "Canary"))
        item = self.binaryPropTable_4.item(7, 0)
        item.setText(_translate("MainWindow", "Crypto"))
        item = self.binaryPropTable_4.item(8, 0)
        item.setText(_translate("MainWindow", "Nx"))
        item = self.binaryPropTable_4.item(9, 0)
        item.setText(_translate("MainWindow", "Pic"))
        item = self.binaryPropTable_4.item(10, 0)
        item.setText(_translate("MainWindow", "Relocs"))
        item = self.binaryPropTable_4.item(11, 0)
        item.setText(_translate("MainWindow", "Relro"))
        item = self.binaryPropTable_4.item(12, 0)
        item.setText(_translate("MainWindow", "Stripped"))
        self.binaryPropTable_4.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PoiTab), _translate("MainWindow", "Points of Interest"))
        self.project_view_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Project View</span></p></body></html>"))
        self.search_box_5.setPlaceholderText(_translate("MainWindow", "Search Project"))
        self.existing_projects_5.setSortingEnabled(False)
        __sortingEnabled = self.existing_projects_5.isSortingEnabled()
        self.existing_projects_5.setSortingEnabled(False)
        item = self.existing_projects_5.item(0)
        item.setText(_translate("MainWindow", "Project A"))
        item = self.existing_projects_5.item(1)
        item.setText(_translate("MainWindow", "Project B"))
        item = self.existing_projects_5.item(2)
        item.setText(_translate("MainWindow", "Project C"))
        item = self.existing_projects_5.item(3)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_5.item(4)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_5.item(5)
        item.setText(_translate("MainWindow", "..."))
        item = self.existing_projects_5.item(6)
        item.setText(_translate("MainWindow", "Project X"))
        self.existing_projects_5.setSortingEnabled(__sortingEnabled)
        self.new_project_5.setText(_translate("MainWindow", "New"))
        self.DetailedProjectView_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Project View</span></p></body></html>"))
        self.binary_properties_5.setText(_translate("MainWindow", "Binary File \n"
"Properties"))
        self.project_name_5.setText(_translate("MainWindow", "Project Name"))
        self.project_description_5.setText(_translate("MainWindow", "Project \n"
"Description"))
        self.browse_5.setText(_translate("MainWindow", "Browse"))
        self.save_5.setText(_translate("MainWindow", "Save"))
        self.delete_6.setText(_translate("MainWindow", "Delete"))
        self.file_path_5.setText(_translate("MainWindow", "Binary File Path"))
        item = self.binaryPropTable_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.binaryPropTable_5.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.binaryPropTable_5.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.binaryPropTable_5.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.binaryPropTable_5.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.binaryPropTable_5.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.binaryPropTable_5.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.binaryPropTable_5.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.binaryPropTable_5.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.binaryPropTable_5.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.binaryPropTable_5.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.binaryPropTable_5.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.binaryPropTable_5.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.binaryPropTable_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.binaryPropTable_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.binaryPropTable_5.isSortingEnabled()
        self.binaryPropTable_5.setSortingEnabled(False)
        item = self.binaryPropTable_5.item(0, 0)
        item.setText(_translate("MainWindow", "OS"))
        item = self.binaryPropTable_5.item(1, 0)
        item.setText(_translate("MainWindow", "Binary Type"))
        item = self.binaryPropTable_5.item(2, 0)
        item.setText(_translate("MainWindow", "Machine"))
        item = self.binaryPropTable_5.item(3, 0)
        item.setText(_translate("MainWindow", "Class"))
        item = self.binaryPropTable_5.item(4, 0)
        item.setText(_translate("MainWindow", "Bits"))
        item = self.binaryPropTable_5.item(5, 0)
        item.setText(_translate("MainWindow", "Language"))
        item = self.binaryPropTable_5.item(6, 0)
        item.setText(_translate("MainWindow", "Canary"))
        item = self.binaryPropTable_5.item(7, 0)
        item.setText(_translate("MainWindow", "Crypto"))
        item = self.binaryPropTable_5.item(8, 0)
        item.setText(_translate("MainWindow", "Nx"))
        item = self.binaryPropTable_5.item(9, 0)
        item.setText(_translate("MainWindow", "Pic"))
        item = self.binaryPropTable_5.item(10, 0)
        item.setText(_translate("MainWindow", "Relocs"))
        item = self.binaryPropTable_5.item(11, 0)
        item.setText(_translate("MainWindow", "Relro"))
        item = self.binaryPropTable_5.item(12, 0)
        item.setText(_translate("MainWindow", "Stripped"))
        self.binaryPropTable_5.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documentationTab), _translate("MainWindow", "Documentation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
