# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 695)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.projectTab = QtWidgets.QWidget()
        self.projectTab.setAutoFillBackground(True)
        self.projectTab.setStyleSheet("")
        self.projectTab.setObjectName("projectTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.projectTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mainGrid = QtWidgets.QGridLayout()
        self.mainGrid.setObjectName("mainGrid")
        self.titleGrid = QtWidgets.QGridLayout()
        self.titleGrid.setObjectName("titleGrid")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label = QtWidgets.QLabel(self.projectTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.gridFrame_2 = QtWidgets.QFrame(self.projectTab)
        self.gridFrame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.gridFrame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.listWidget = QtWidgets.QListWidget(self.gridFrame_2)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.pushButton = QtWidgets.QPushButton(self.gridFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout_10.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.gridFrame_2, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_2 = QtWidgets.QLabel(self.projectTab)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridFrame_7 = QtWidgets.QFrame(self.projectTab)
        self.gridFrame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame_7.setObjectName("gridFrame_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridFrame_7)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.textEdit = QtWidgets.QTextEdit(self.gridFrame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_15.addWidget(self.textEdit, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridFrame_7)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_15.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_15.addWidget(self.label_5, 2, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.gridFrame_7)
        self.tableView.setObjectName("tableView")
        self.gridLayout_15.addWidget(self.tableView, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_15.addWidget(self.label_4, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridFrame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_15.addWidget(self.pushButton_3, 4, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridFrame_7)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_15.addWidget(self.pushButton_2, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 3, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridFrame_7)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(True)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_15.addWidget(self.pushButton_4, 4, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridFrame_7)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_15.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.gridLayout_15.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.gridFrame_7, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 2)
        self.gridLayout_6.setColumnStretch(1, 8)
        self.titleGrid.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.mainGrid.addLayout(self.titleGrid, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.mainGrid, 0, 0, 1, 1)
        self.tabWidget.addTab(self.projectTab, "")
        self.analysisTab = QtWidgets.QWidget()
        self.analysisTab.setObjectName("analysisTab")
        self.tabWidget.addTab(self.analysisTab, "")
        self.pluginTab = QtWidgets.QWidget()
        self.pluginTab.setObjectName("pluginTab")
        self.tabWidget.addTab(self.pluginTab, "")
        self.PoiTab = QtWidgets.QWidget()
        self.PoiTab.setObjectName("PoiTab")
        self.tabWidget.addTab(self.PoiTab, "")
        self.documentationTab = QtWidgets.QWidget()
        self.documentationTab.setObjectName("documentationTab")
        self.tabWidget.addTab(self.documentationTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Project View</span></p></body></html>"))
        self.lineEdit.setText(_translate("MainWindow", "Search "))
        self.pushButton.setText(_translate("MainWindow", "New"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Project View</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Binary File Path"))
        self.label_4.setText(_translate("MainWindow", "Project \n"
"Description"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))
        self.pushButton_2.setText(_translate("MainWindow", "Browse"))
        self.label_6.setText(_translate("MainWindow", "Binary File \n"
"Properties"))
        self.pushButton_4.setText(_translate("MainWindow", "Save"))
        self.label_3.setText(_translate("MainWindow", "Project \n"
" Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("MainWindow", "Project"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysisTab), _translate("MainWindow", "Analysis "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pluginTab), _translate("MainWindow", "Plugin Management"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PoiTab), _translate("MainWindow", "Points of Interest"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documentationTab), _translate("MainWindow", "Documentation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
