# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/RedFlash05/AppData/Local/Temp/mainWindowBrianJgFjup.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(892, 695)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.projectTab = QtWidgets.QWidget()
        self.projectTab.setAutoFillBackground(True)
        self.projectTab.setStyleSheet("")
        self.projectTab.setObjectName("projectTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.projectTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mainGrid = QtWidgets.QGridLayout()
        self.mainGrid.setObjectName("mainGrid")
        self.titleGrid = QtWidgets.QGridLayout()
        self.titleGrid.setObjectName("titleGrid")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label = QtWidgets.QLabel(self.projectTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.gridFrame_2 = QtWidgets.QFrame(self.projectTab)
        self.gridFrame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.gridFrame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.listWidget = QtWidgets.QListWidget(self.gridFrame_2)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.pushButton = QtWidgets.QPushButton(self.gridFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout_10.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.gridFrame_2, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_2 = QtWidgets.QLabel(self.projectTab)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridFrame_7 = QtWidgets.QFrame(self.projectTab)
        self.gridFrame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame_7.setObjectName("gridFrame_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridFrame_7)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.textEdit = QtWidgets.QTextEdit(self.gridFrame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_15.addWidget(self.textEdit, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridFrame_7)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_15.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_15.addWidget(self.label_5, 2, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.gridFrame_7)
        self.tableView.setObjectName("tableView")
        self.gridLayout_15.addWidget(self.tableView, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_15.addWidget(self.label_4, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridFrame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_15.addWidget(self.pushButton_3, 4, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridFrame_7)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_15.addWidget(self.pushButton_2, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 3, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridFrame_7)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(True)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_15.addWidget(self.pushButton_4, 4, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridFrame_7)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_15.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.gridLayout_15.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.gridFrame_7, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 2)
        self.gridLayout_6.setColumnStretch(1, 8)
        self.titleGrid.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.mainGrid.addLayout(self.titleGrid, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.mainGrid, 0, 0, 1, 1)
        self.tabWidget.addTab(self.projectTab, "")
        self.analysisTab = QtWidgets.QWidget()
        self.analysisTab.setObjectName("analysisTab")
        self.tabWidget.addTab(self.analysisTab, "")
        self.pluginTab = QtWidgets.QWidget()
        self.pluginTab.setObjectName("pluginTab")
        self.tabWidget.addTab(self.pluginTab, "")
        self.PoiTab = QtWidgets.QWidget()
        self.PoiTab.setAutoFillBackground(True)
        self.PoiTab.setObjectName("PoiTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.PoiTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.titleGrid_5 = QtWidgets.QGridLayout()
        self.titleGrid_5.setObjectName("titleGrid_5")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gridFrame_6 = QtWidgets.QFrame(self.PoiTab)
        self.gridFrame_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.gridFrame_6.setObjectName("gridFrame_6")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.gridFrame_6)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.POI_NewButton = QtWidgets.QPushButton(self.gridFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.POI_NewButton.sizePolicy().hasHeightForWidth())
        self.POI_NewButton.setSizePolicy(sizePolicy)
        self.POI_NewButton.setAutoFillBackground(False)
        self.POI_NewButton.setObjectName("POI_NewButton")
        self.gridLayout_29.addWidget(self.POI_NewButton, 2, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.POI_List = QtWidgets.QListWidget(self.gridFrame_6)
        self.POI_List.setObjectName("POI_List")
        item = QtWidgets.QListWidgetItem()
        self.POI_List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.POI_List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.POI_List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.POI_List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.POI_List.addItem(item)
        self.verticalLayout_8.addWidget(self.POI_List)
        self.gridLayout_29.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        self.POI_LineEdit = QtWidgets.QLineEdit(self.gridFrame_6)
        self.POI_LineEdit.setObjectName("POI_LineEdit")
        self.gridLayout_29.addWidget(self.POI_LineEdit, 0, 1, 1, 1)
        self.gridLayout_28.addWidget(self.gridFrame_6, 1, 0, 1, 1)
        self.POI_LabelView = QtWidgets.QLabel(self.PoiTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.POI_LabelView.setFont(font)
        self.POI_LabelView.setAutoFillBackground(False)
        self.POI_LabelView.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.POI_LabelView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.POI_LabelView.setAlignment(QtCore.Qt.AlignCenter)
        self.POI_LabelView.setObjectName("POI_LabelView")
        self.gridLayout_28.addWidget(self.POI_LabelView, 0, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_28, 0, 0, 1, 1)
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.POI_DetailLabel = QtWidgets.QLabel(self.PoiTab)
        self.POI_DetailLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.POI_DetailLabel.sizePolicy().hasHeightForWidth())
        self.POI_DetailLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.POI_DetailLabel.setFont(font)
        self.POI_DetailLabel.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.POI_DetailLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.POI_DetailLabel.setTextFormat(QtCore.Qt.RichText)
        self.POI_DetailLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.POI_DetailLabel.setObjectName("POI_DetailLabel")
        self.gridLayout_30.addWidget(self.POI_DetailLabel, 0, 0, 1, 1)
        self.gridFrame_11 = QtWidgets.QFrame(self.PoiTab)
        self.gridFrame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame_11.setObjectName("gridFrame_11")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.gridFrame_11)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.POI_Label2 = QtWidgets.QLabel(self.gridFrame_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.POI_Label2.setFont(font)
        self.POI_Label2.setObjectName("POI_Label2")
        self.gridLayout_31.addWidget(self.POI_Label2, 2, 0, 1, 1)
        self.POI_Del = QtWidgets.QPushButton(self.gridFrame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.POI_Del.sizePolicy().hasHeightForWidth())
        self.POI_Del.setSizePolicy(sizePolicy)
        self.POI_Del.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.POI_Del.setObjectName("POI_Del")
        self.gridLayout_31.addWidget(self.POI_Del, 4, 0, 1, 1)
        self.POI_Combo2 = QtWidgets.QComboBox(self.gridFrame_11)
        self.POI_Combo2.setObjectName("POI_Combo2")
        self.POI_Combo2.addItem("")
        self.gridLayout_31.addWidget(self.POI_Combo2, 2, 1, 1, 1)
        self.POI_Combo1_2 = QtWidgets.QComboBox(self.gridFrame_11)
        self.POI_Combo1_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.POI_Combo1_2.setObjectName("POI_Combo1_2")
        self.POI_Combo1_2.addItem("")
        self.gridLayout_31.addWidget(self.POI_Combo1_2, 0, 1, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.POI_Label1 = QtWidgets.QLabel(self.gridFrame_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.POI_Label1.setFont(font)
        self.POI_Label1.setObjectName("POI_Label1")
        self.verticalLayout_9.addWidget(self.POI_Label1)
        self.gridLayout_31.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.POI_Panel = QtWidgets.QTableView(self.gridFrame_11)
        self.POI_Panel.setObjectName("POI_Panel")
        self.gridLayout_31.addWidget(self.POI_Panel, 3, 0, 1, 3)
        self.POI_Save = QtWidgets.QPushButton(self.gridFrame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.POI_Save.sizePolicy().hasHeightForWidth())
        self.POI_Save.setSizePolicy(sizePolicy)
        self.POI_Save.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.POI_Save.setAutoDefault(False)
        self.POI_Save.setDefault(True)
        self.POI_Save.setFlat(False)
        self.POI_Save.setObjectName("POI_Save")
        self.gridLayout_31.addWidget(self.POI_Save, 4, 2, 1, 1)
        self.gridLayout_30.addWidget(self.gridFrame_11, 2, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_30, 0, 1, 1, 1)
        self.gridLayout_27.setColumnStretch(0, 2)
        self.gridLayout_27.setColumnStretch(1, 8)
        self.titleGrid_5.addLayout(self.gridLayout_27, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.titleGrid_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.PoiTab, "")
        self.documentationTab = QtWidgets.QWidget()
        self.documentationTab.setObjectName("documentationTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.documentationTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mainGrid_2 = QtWidgets.QGridLayout()
        self.mainGrid_2.setObjectName("mainGrid_2")
        self.titleGrid_2 = QtWidgets.QGridLayout()
        self.titleGrid_2.setObjectName("titleGrid_2")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.documentation_view = QtWidgets.QLabel(self.documentationTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.documentation_view.setFont(font)
        self.documentation_view.setAutoFillBackground(False)
        self.documentation_view.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.documentation_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.documentation_view.setAlignment(QtCore.Qt.AlignCenter)
        self.documentation_view.setObjectName("documentation_view")
        self.gridLayout_11.addWidget(self.documentation_view, 0, 0, 1, 1)
        self.gridFrame_3 = QtWidgets.QFrame(self.documentationTab)
        self.gridFrame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.documentation_lineEdit = QtWidgets.QLineEdit(self.gridFrame_3)
        self.documentation_lineEdit.setObjectName("documentation_lineEdit")
        self.verticalLayout_2.addWidget(self.documentation_lineEdit)
        self.documentation_list = QtWidgets.QListWidget(self.gridFrame_3)
        self.documentation_list.setObjectName("documentation_list")
        item = QtWidgets.QListWidgetItem()
        self.documentation_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.documentation_list.addItem(item)
        self.verticalLayout_2.addWidget(self.documentation_list)
        self.gridLayout_12.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.gridFrame_3, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.documentation_detail = QtWidgets.QLabel(self.documentationTab)
        self.documentation_detail.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.documentation_detail.sizePolicy().hasHeightForWidth())
        self.documentation_detail.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.documentation_detail.setFont(font)
        self.documentation_detail.setStyleSheet("background-color: rgba(173,216,230 ,1 )")
        self.documentation_detail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.documentation_detail.setTextFormat(QtCore.Qt.RichText)
        self.documentation_detail.setAlignment(QtCore.Qt.AlignCenter)
        self.documentation_detail.setObjectName("documentation_detail")
        self.gridLayout_13.addWidget(self.documentation_detail, 0, 0, 1, 1)
        self.gridFrame_8 = QtWidgets.QFrame(self.documentationTab)
        self.gridFrame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame_8.setObjectName("gridFrame_8")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gridFrame_8)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.documentation_panel = QtWidgets.QTableView(self.gridFrame_8)
        self.documentation_panel.setObjectName("documentation_panel")
        self.gridLayout_16.addWidget(self.documentation_panel, 1, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_16.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.gridFrame_8, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_13, 0, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 2)
        self.gridLayout_7.setColumnStretch(1, 8)
        self.titleGrid_2.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.mainGrid_2.addLayout(self.titleGrid_2, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.mainGrid_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.documentationTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Project View</span></p></body></html>"))
        self.lineEdit.setText(_translate("MainWindow", "Search "))
        self.pushButton.setText(_translate("MainWindow", "New"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Project View</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Binary File Path"))
        self.label_4.setText(_translate("MainWindow", "Project \n"
"Description"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))
        self.pushButton_2.setText(_translate("MainWindow", "Browse"))
        self.label_6.setText(_translate("MainWindow", "Binary File \n"
"Properties"))
        self.pushButton_4.setText(_translate("MainWindow", "Save"))
        self.label_3.setText(_translate("MainWindow", "Project \n"
" Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("MainWindow", "Project"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysisTab), _translate("MainWindow", "Analysis "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pluginTab), _translate("MainWindow", "Plugin Management"))
        self.POI_NewButton.setText(_translate("MainWindow", "New"))
        __sortingEnabled = self.POI_List.isSortingEnabled()
        self.POI_List.setSortingEnabled(False)
        item = self.POI_List.item(0)
        item.setText(_translate("MainWindow", "Point of interest A"))
        item = self.POI_List.item(1)
        item.setText(_translate("MainWindow", "Point of interest B"))
        item = self.POI_List.item(2)
        item.setText(_translate("MainWindow", "Point of interest C"))
        item = self.POI_List.item(3)
        item.setText(_translate("MainWindow", "             ... "))
        item = self.POI_List.item(4)
        item.setText(_translate("MainWindow", "Point of interest X"))
        self.POI_List.setSortingEnabled(__sortingEnabled)
        self.POI_LineEdit.setText(_translate("MainWindow", "Points of Interest"))
        self.POI_LabelView.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Point of Interest View</span></p></body></html>"))
        self.POI_DetailLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Point of Interest View</span></p></body></html>"))
        self.POI_Label2.setText(_translate("MainWindow", "Point of Interest Type"))
        self.POI_Del.setText(_translate("MainWindow", "Delete"))
        self.POI_Combo2.setItemText(0, _translate("MainWindow", "Type"))
        self.POI_Combo1_2.setItemText(0, _translate("MainWindow", "Existing Plugin"))
        self.POI_Label1.setText(_translate("MainWindow", "Plugin"))
        self.POI_Save.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PoiTab), _translate("MainWindow", "Points of Interest"))
        self.documentation_view.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Document View</span></p></body></html>"))
        self.documentation_lineEdit.setText(_translate("MainWindow", "Document"))
        __sortingEnabled = self.documentation_list.isSortingEnabled()
        self.documentation_list.setSortingEnabled(False)
        item = self.documentation_list.item(0)
        item.setText(_translate("MainWindow", "Beat Documentation"))
        item = self.documentation_list.item(1)
        item.setText(_translate("MainWindow", "Plugin Structure"))
        self.documentation_list.setSortingEnabled(__sortingEnabled)
        self.documentation_detail.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Detailed Document View</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documentationTab), _translate("MainWindow", "Documentation"))

